<?php

declare(strict_types=1);

namespace Paqtcom\Simplicate\Normalizer;

use ArrayObject;
use Jane\Component\JsonSchemaRuntime\Reference;
use Paqtcom\Simplicate\Model\Absence;
use Paqtcom\Simplicate\Model\AbsenceType;
use Paqtcom\Simplicate\Model\Accountancy;
use Paqtcom\Simplicate\Model\Address;
use Paqtcom\Simplicate\Model\Administration;
use Paqtcom\Simplicate\Model\App;
use Paqtcom\Simplicate\Model\AppReceivers;
use Paqtcom\Simplicate\Model\AppReceiverSetting;
use Paqtcom\Simplicate\Model\Approval;
use Paqtcom\Simplicate\Model\ApprovalStatus;
use Paqtcom\Simplicate\Model\Assignment;
use Paqtcom\Simplicate\Model\AssignmentBudget;
use Paqtcom\Simplicate\Model\AssignmentBudgetInfo;
use Paqtcom\Simplicate\Model\AssignmentBudgetInfoFuturePast;
use Paqtcom\Simplicate\Model\AssignmentBudgetInfoMetaData;
use Paqtcom\Simplicate\Model\AssignmentStatus;
use Paqtcom\Simplicate\Model\Attachment;
use Paqtcom\Simplicate\Model\AttachmentType;
use Paqtcom\Simplicate\Model\Avatar;
use Paqtcom\Simplicate\Model\AvatarPublic;
use Paqtcom\Simplicate\Model\AvatarSimple;
use Paqtcom\Simplicate\Model\BaseHours;
use Paqtcom\Simplicate\Model\BaseSetting;
use Paqtcom\Simplicate\Model\Budget;
use Paqtcom\Simplicate\Model\BudgetCosts;
use Paqtcom\Simplicate\Model\BudgetHours;
use Paqtcom\Simplicate\Model\BudgetTotal;
use Paqtcom\Simplicate\Model\CalendarItem;
use Paqtcom\Simplicate\Model\CivilStatus;
use Paqtcom\Simplicate\Model\Comment;
use Paqtcom\Simplicate\Model\ContactPerson;
use Paqtcom\Simplicate\Model\ContentField;
use Paqtcom\Simplicate\Model\Contract;
use Paqtcom\Simplicate\Model\ContractType;
use Paqtcom\Simplicate\Model\Correction;
use Paqtcom\Simplicate\Model\Country;
use Paqtcom\Simplicate\Model\CreatedBy;
use Paqtcom\Simplicate\Model\Creator;
use Paqtcom\Simplicate\Model\CurrentTask;
use Paqtcom\Simplicate\Model\CurrentTaskEmployee;
use Paqtcom\Simplicate\Model\CustomerGroup;
use Paqtcom\Simplicate\Model\CustomField;
use Paqtcom\Simplicate\Model\CustomFieldGroup;
use Paqtcom\Simplicate\Model\CustomFieldModel;
use Paqtcom\Simplicate\Model\CustomFieldOption;
use Paqtcom\Simplicate\Model\CustomFieldType;
use Paqtcom\Simplicate\Model\DateTimeRange;
use Paqtcom\Simplicate\Model\Debtor;
use Paqtcom\Simplicate\Model\DebtorList;
use Paqtcom\Simplicate\Model\DefaultAction;
use Paqtcom\Simplicate\Model\DefaultService;
use Paqtcom\Simplicate\Model\DefaultTask;
use Paqtcom\Simplicate\Model\DefaultWorkflow;
use Paqtcom\Simplicate\Model\DefaultWorkflowGroup;
use Paqtcom\Simplicate\Model\Document;
use Paqtcom\Simplicate\Model\DocumentType;
use Paqtcom\Simplicate\Model\DocumentTypeSimple;
use Paqtcom\Simplicate\Model\EmailAttachment;
use Paqtcom\Simplicate\Model\EmailMessage;
use Paqtcom\Simplicate\Model\Employee;
use Paqtcom\Simplicate\Model\EmployeeStatus;
use Paqtcom\Simplicate\Model\EmployeeType;
use Paqtcom\Simplicate\Model\EmploymentType;
use Paqtcom\Simplicate\Model\Expense;
use Paqtcom\Simplicate\Model\ExpenseAttachment;
use Paqtcom\Simplicate\Model\ExternalItemMetadata;
use Paqtcom\Simplicate\Model\ExternalItemMetadataConfiguration;
use Paqtcom\Simplicate\Model\ExternalList;
use Paqtcom\Simplicate\Model\ExternalListTag;
use Paqtcom\Simplicate\Model\Feature;
use Paqtcom\Simplicate\Model\Filter;
use Paqtcom\Simplicate\Model\Gender;
use Paqtcom\Simplicate\Model\GetAbsence;
use Paqtcom\Simplicate\Model\GetAbsenceType;
use Paqtcom\Simplicate\Model\GetAddress;
use Paqtcom\Simplicate\Model\GetApproval;
use Paqtcom\Simplicate\Model\GetApprovalStatus;
use Paqtcom\Simplicate\Model\GetAssignment;
use Paqtcom\Simplicate\Model\GetAssignmentSimple;
use Paqtcom\Simplicate\Model\GetAssignmentStatus;
use Paqtcom\Simplicate\Model\GetBasicPersonSimple;
use Paqtcom\Simplicate\Model\GetCivilStatus;
use Paqtcom\Simplicate\Model\GetContactPerson;
use Paqtcom\Simplicate\Model\GetContactSimple;
use Paqtcom\Simplicate\Model\GetContract;
use Paqtcom\Simplicate\Model\GetCustomField;
use Paqtcom\Simplicate\Model\GetDebtor;
use Paqtcom\Simplicate\Model\GetDefaultAction;
use Paqtcom\Simplicate\Model\GetDefaultService;
use Paqtcom\Simplicate\Model\GetDefaultTask;
use Paqtcom\Simplicate\Model\GetDefaultWorkflow;
use Paqtcom\Simplicate\Model\GetDefaultWorkflowGroup;
use Paqtcom\Simplicate\Model\GetDocument;
use Paqtcom\Simplicate\Model\GetDocumentType;
use Paqtcom\Simplicate\Model\GetEmployee;
use Paqtcom\Simplicate\Model\GetEmployeeSimple;
use Paqtcom\Simplicate\Model\GetHours;
use Paqtcom\Simplicate\Model\GetHoursHoursProjectService;
use Paqtcom\Simplicate\Model\GetHoursProjectService;
use Paqtcom\Simplicate\Model\GetHoursSimple;
use Paqtcom\Simplicate\Model\GetHoursType;
use Paqtcom\Simplicate\Model\GetInterest;
use Paqtcom\Simplicate\Model\GetInvoice;
use Paqtcom\Simplicate\Model\GetInvoiceLine;
use Paqtcom\Simplicate\Model\GetInvoiceReminder;
use Paqtcom\Simplicate\Model\GetInvoiceSimple;
use Paqtcom\Simplicate\Model\GetLeave;
use Paqtcom\Simplicate\Model\GetLeaveType;
use Paqtcom\Simplicate\Model\GetMessage;
use Paqtcom\Simplicate\Model\GetMileage;
use Paqtcom\Simplicate\Model\GetMileageSimple;
use Paqtcom\Simplicate\Model\GetMyOrganizationProfileSimple;
use Paqtcom\Simplicate\Model\GetOrganization;
use Paqtcom\Simplicate\Model\GetOrganizationDebtorSimple;
use Paqtcom\Simplicate\Model\GetOrganizationSimple;
use Paqtcom\Simplicate\Model\GetPayment;
use Paqtcom\Simplicate\Model\GetPaymentTerm;
use Paqtcom\Simplicate\Model\GetPerson;
use Paqtcom\Simplicate\Model\GetPersonDebtorSimple;
use Paqtcom\Simplicate\Model\GetPersonSimple;
use Paqtcom\Simplicate\Model\GetProject;
use Paqtcom\Simplicate\Model\GetProjectService;
use Paqtcom\Simplicate\Model\GetProjectServiceCostType;
use Paqtcom\Simplicate\Model\GetProjectServiceHoursType;
use Paqtcom\Simplicate\Model\GetProjectServiceSimple;
use Paqtcom\Simplicate\Model\GetProjectSimple;
use Paqtcom\Simplicate\Model\GetProposition;
use Paqtcom\Simplicate\Model\GetPurchaseType;
use Paqtcom\Simplicate\Model\GetQuote;
use Paqtcom\Simplicate\Model\GetReminderSet;
use Paqtcom\Simplicate\Model\GetReminderSetSimple;
use Paqtcom\Simplicate\Model\GetReviewByWeek;
use Paqtcom\Simplicate\Model\GetReviewByWeekDetails;
use Paqtcom\Simplicate\Model\GetReviewByWeekId;
use Paqtcom\Simplicate\Model\GetSales;
use Paqtcom\Simplicate\Model\GetSalesService;
use Paqtcom\Simplicate\Model\GetSalesServiceCostType;
use Paqtcom\Simplicate\Model\GetSalesServiceHoursType;
use Paqtcom\Simplicate\Model\GetSeparateInvoiceRecipient;
use Paqtcom\Simplicate\Model\GetService;
use Paqtcom\Simplicate\Model\GetServiceCostType;
use Paqtcom\Simplicate\Model\GetSharedItem;
use Paqtcom\Simplicate\Model\GetSimpleDefaultTask;
use Paqtcom\Simplicate\Model\GetSimpleDefaultWorkflow;
use Paqtcom\Simplicate\Model\GetTeam;
use Paqtcom\Simplicate\Model\GetTeamSimple;
use Paqtcom\Simplicate\Model\GetTimer;
use Paqtcom\Simplicate\Model\GetTimesheetRow;
use Paqtcom\Simplicate\Model\GetTimesheetRowItemtype;
use Paqtcom\Simplicate\Model\GetTimesheetRowOrganizationRelation;
use Paqtcom\Simplicate\Model\GetTimesheetRowPersonRelation;
use Paqtcom\Simplicate\Model\GetTimesheetRowProject;
use Paqtcom\Simplicate\Model\GetTimesheetRowProjectService;
use Paqtcom\Simplicate\Model\GetTimetable;
use Paqtcom\Simplicate\Model\GetWorkflow;
use Paqtcom\Simplicate\Model\Hours;
use Paqtcom\Simplicate\Model\HoursType;
use Paqtcom\Simplicate\Model\HrmGetLeaveType;
use Paqtcom\Simplicate\Model\HrmPostTeam;
use Paqtcom\Simplicate\Model\Inbox;
use Paqtcom\Simplicate\Model\Industry;
use Paqtcom\Simplicate\Model\Installment;
use Paqtcom\Simplicate\Model\Interest;
use Paqtcom\Simplicate\Model\Invoice;
use Paqtcom\Simplicate\Model\InvoiceLine;
use Paqtcom\Simplicate\Model\InvoiceStatus;
use Paqtcom\Simplicate\Model\InvoiceTemplate;
use Paqtcom\Simplicate\Model\IsSatisfied;
use Paqtcom\Simplicate\Model\IsSatisfiedReason;
use Paqtcom\Simplicate\Model\Journal;
use Paqtcom\Simplicate\Model\JournalLine;
use Paqtcom\Simplicate\Model\JournalVat;
use Paqtcom\Simplicate\Model\Leave;
use Paqtcom\Simplicate\Model\LeaveBalance;
use Paqtcom\Simplicate\Model\LeaveStatus;
use Paqtcom\Simplicate\Model\LeaveType;
use Paqtcom\Simplicate\Model\LinkedTo;
use Paqtcom\Simplicate\Model\LinkedToEntity;
use Paqtcom\Simplicate\Model\Log;
use Paqtcom\Simplicate\Model\LostToCompetitor;
use Paqtcom\Simplicate\Model\MailingList;
use Paqtcom\Simplicate\Model\Message;
use Paqtcom\Simplicate\Model\MessageType;
use Paqtcom\Simplicate\Model\MetaData;
use Paqtcom\Simplicate\Model\Mileage;
use Paqtcom\Simplicate\Model\MileageType;
use Paqtcom\Simplicate\Model\MyOrganizationProfile;
use Paqtcom\Simplicate\Model\Organization;
use Paqtcom\Simplicate\Model\OrganizationContact;
use Paqtcom\Simplicate\Model\OrganizationSize;
use Paqtcom\Simplicate\Model\Payment;
use Paqtcom\Simplicate\Model\PaymentTerm;
use Paqtcom\Simplicate\Model\Person;
use Paqtcom\Simplicate\Model\PersonContact;
use Paqtcom\Simplicate\Model\PersonMailingList;
use Paqtcom\Simplicate\Model\PkRestResult;
use Paqtcom\Simplicate\Model\PostAbsence;
use Paqtcom\Simplicate\Model\PostAddress;
use Paqtcom\Simplicate\Model\PostApproval;
use Paqtcom\Simplicate\Model\PostAssignment;
use Paqtcom\Simplicate\Model\PostAttachment;
use Paqtcom\Simplicate\Model\PostCalendarItem;
use Paqtcom\Simplicate\Model\PostChunked;
use Paqtcom\Simplicate\Model\PostContactOrganizationFk;
use Paqtcom\Simplicate\Model\PostContactPerson;
use Paqtcom\Simplicate\Model\PostContactPersonFk;
use Paqtcom\Simplicate\Model\PostContactPersonProperties;
use Paqtcom\Simplicate\Model\PostCustomFieldValue;
use Paqtcom\Simplicate\Model\PostDebtor;
use Paqtcom\Simplicate\Model\PostDefaultService;
use Paqtcom\Simplicate\Model\PostDocument;
use Paqtcom\Simplicate\Model\PostDocumentLinkedTo;
use Paqtcom\Simplicate\Model\PostDuplicateSales;
use Paqtcom\Simplicate\Model\PostEmployee;
use Paqtcom\Simplicate\Model\PostEmployeeFk;
use Paqtcom\Simplicate\Model\PostEmployeeStatusFk;
use Paqtcom\Simplicate\Model\PostExpense;
use Paqtcom\Simplicate\Model\PostHours;
use Paqtcom\Simplicate\Model\PostHoursType;
use Paqtcom\Simplicate\Model\PostInterest;
use Paqtcom\Simplicate\Model\PostInvoice;
use Paqtcom\Simplicate\Model\PostInvoiceLine;
use Paqtcom\Simplicate\Model\PostLeave;
use Paqtcom\Simplicate\Model\PostMerger;
use Paqtcom\Simplicate\Model\PostMergerCompare;
use Paqtcom\Simplicate\Model\PostMessage;
use Paqtcom\Simplicate\Model\PostMessageLinkedTo;
use Paqtcom\Simplicate\Model\PostMileage;
use Paqtcom\Simplicate\Model\PostOrganization;
use Paqtcom\Simplicate\Model\PostOrganizationFk;
use Paqtcom\Simplicate\Model\PostPerson;
use Paqtcom\Simplicate\Model\PostProject;
use Paqtcom\Simplicate\Model\PostProjectService;
use Paqtcom\Simplicate\Model\PostProjectServiceHoursType;
use Paqtcom\Simplicate\Model\PostPurchaseType;
use Paqtcom\Simplicate\Model\PostQuote;
use Paqtcom\Simplicate\Model\PostQuoteTemplate;
use Paqtcom\Simplicate\Model\PostSales;
use Paqtcom\Simplicate\Model\PostSalesService;
use Paqtcom\Simplicate\Model\PostSeparateInvoiceRecipient;
use Paqtcom\Simplicate\Model\PostService;
use Paqtcom\Simplicate\Model\PostSharedItem;
use Paqtcom\Simplicate\Model\PostSubmission;
use Paqtcom\Simplicate\Model\PostTeam;
use Paqtcom\Simplicate\Model\PostTimer;
use Paqtcom\Simplicate\Model\PostTimesheetRow;
use Paqtcom\Simplicate\Model\PostTimetable;
use Paqtcom\Simplicate\Model\PostVatClassFk;
use Paqtcom\Simplicate\Model\PostWorkflow;
use Paqtcom\Simplicate\Model\Project;
use Paqtcom\Simplicate\Model\ProjectAssignmentDeleteResultRest;
use Paqtcom\Simplicate\Model\ProjectEmployee;
use Paqtcom\Simplicate\Model\ProjectManager;
use Paqtcom\Simplicate\Model\ProjectServiceCostType;
use Paqtcom\Simplicate\Model\ProjectServiceHoursType;
use Paqtcom\Simplicate\Model\ProjectStatus;
use Paqtcom\Simplicate\Model\Purchase;
use Paqtcom\Simplicate\Model\PurchaseType;
use Paqtcom\Simplicate\Model\PutAssignment;
use Paqtcom\Simplicate\Model\PutChunked;
use Paqtcom\Simplicate\Model\PutContactPerson;
use Paqtcom\Simplicate\Model\PutDocument;
use Paqtcom\Simplicate\Model\PutEmployee;
use Paqtcom\Simplicate\Model\PutMileage;
use Paqtcom\Simplicate\Model\PutProjectService;
use Paqtcom\Simplicate\Model\PutQuoteEmail;
use Paqtcom\Simplicate\Model\PutTimer;
use Paqtcom\Simplicate\Model\PutTimetable;
use Paqtcom\Simplicate\Model\Quote;
use Paqtcom\Simplicate\Model\QuoteContentBlock;
use Paqtcom\Simplicate\Model\QuotePortalLabel;
use Paqtcom\Simplicate\Model\QuoteSalesService;
use Paqtcom\Simplicate\Model\QuoteStatus;
use Paqtcom\Simplicate\Model\QuoteTemplate;
use Paqtcom\Simplicate\Model\QuotetemplateConfigurationMetaData;
use Paqtcom\Simplicate\Model\QuotetemplateMetaData;
use Paqtcom\Simplicate\Model\RecentSalesQuote;
use Paqtcom\Simplicate\Model\RecentSalesQuoteStatus;
use Paqtcom\Simplicate\Model\Recurrence;
use Paqtcom\Simplicate\Model\RelationType;
use Paqtcom\Simplicate\Model\ReminderSet;
use Paqtcom\Simplicate\Model\ReminderSetTemplate;
use Paqtcom\Simplicate\Model\ReminderTemplate;
use Paqtcom\Simplicate\Model\RestBatchValidationError;
use Paqtcom\Simplicate\Model\RestError;
use Paqtcom\Simplicate\Model\RestResultAbsence;
use Paqtcom\Simplicate\Model\RestResultAbsenceMultiple;
use Paqtcom\Simplicate\Model\RestResultAbsenceType;
use Paqtcom\Simplicate\Model\RestResultAbsenceTypes;
use Paqtcom\Simplicate\Model\RestResultAdministration;
use Paqtcom\Simplicate\Model\RestResultAdministrations;
use Paqtcom\Simplicate\Model\RestResultApp;
use Paqtcom\Simplicate\Model\RestResultApproval;
use Paqtcom\Simplicate\Model\RestResultApprovals;
use Paqtcom\Simplicate\Model\RestResultApprovalStatus;
use Paqtcom\Simplicate\Model\RestResultApprovalStatusList;
use Paqtcom\Simplicate\Model\RestResultApps;
use Paqtcom\Simplicate\Model\RestResultCache;
use Paqtcom\Simplicate\Model\RestResultCivilStatus;
use Paqtcom\Simplicate\Model\RestResultCivilStatuses;
use Paqtcom\Simplicate\Model\RestResultContact;
use Paqtcom\Simplicate\Model\RestResultContactPerson;
use Paqtcom\Simplicate\Model\RestResultContactPersons;
use Paqtcom\Simplicate\Model\RestResultContacts;
use Paqtcom\Simplicate\Model\RestResultContract;
use Paqtcom\Simplicate\Model\RestResultContracts;
use Paqtcom\Simplicate\Model\RestResultContractType;
use Paqtcom\Simplicate\Model\RestResultContractTypes;
use Paqtcom\Simplicate\Model\RestResultCountries;
use Paqtcom\Simplicate\Model\RestResultCountry;
use Paqtcom\Simplicate\Model\RestResultCustomField;
use Paqtcom\Simplicate\Model\RestResultCustomFieldGroup;
use Paqtcom\Simplicate\Model\RestResultCustomFieldGroups;
use Paqtcom\Simplicate\Model\RestResultCustomFieldModel;
use Paqtcom\Simplicate\Model\RestResultCustomFieldModels;
use Paqtcom\Simplicate\Model\RestResultCustomFieldOption;
use Paqtcom\Simplicate\Model\RestResultCustomFieldOptions;
use Paqtcom\Simplicate\Model\RestResultCustomFields;
use Paqtcom\Simplicate\Model\RestResultCustomFieldType;
use Paqtcom\Simplicate\Model\RestResultCustomFieldTypes;
use Paqtcom\Simplicate\Model\RestResultDateTimeRange;
use Paqtcom\Simplicate\Model\RestResultDebtorList;
use Paqtcom\Simplicate\Model\RestResultDefaultService;
use Paqtcom\Simplicate\Model\RestResultDefaultServices;
use Paqtcom\Simplicate\Model\RestResultDocument;
use Paqtcom\Simplicate\Model\RestResultDocuments;
use Paqtcom\Simplicate\Model\RestResultDocumentType;
use Paqtcom\Simplicate\Model\RestResultDocumentTypes;
use Paqtcom\Simplicate\Model\RestResultEmployee;
use Paqtcom\Simplicate\Model\RestResultEmployeeExpense;
use Paqtcom\Simplicate\Model\RestResultEmployeeExpenseList;
use Paqtcom\Simplicate\Model\RestResultEmployees;
use Paqtcom\Simplicate\Model\RestResultEmployeeType;
use Paqtcom\Simplicate\Model\RestResultEmployeeTypes;
use Paqtcom\Simplicate\Model\RestResultEmploymentType;
use Paqtcom\Simplicate\Model\RestResultEmploymentTypes;
use Paqtcom\Simplicate\Model\RestResultExternalItems;
use Paqtcom\Simplicate\Model\RestResultGender;
use Paqtcom\Simplicate\Model\RestResultGenders;
use Paqtcom\Simplicate\Model\RestResultHour;
use Paqtcom\Simplicate\Model\RestResultHours;
use Paqtcom\Simplicate\Model\RestResultHoursSubmissions;
use Paqtcom\Simplicate\Model\RestResultHoursTimesheetRow;
use Paqtcom\Simplicate\Model\RestResultHoursTimesheetRows;
use Paqtcom\Simplicate\Model\RestResultHourType;
use Paqtcom\Simplicate\Model\RestResultHourTypes;
use Paqtcom\Simplicate\Model\RestResultIndustries;
use Paqtcom\Simplicate\Model\RestResultIndustry;
use Paqtcom\Simplicate\Model\RestResultInterest;
use Paqtcom\Simplicate\Model\RestResultInterests;
use Paqtcom\Simplicate\Model\RestResultInvoice;
use Paqtcom\Simplicate\Model\RestResultInvoices;
use Paqtcom\Simplicate\Model\RestResultInvoiceStatus;
use Paqtcom\Simplicate\Model\RestResultInvoiceStatuses;
use Paqtcom\Simplicate\Model\RestResultJournal;
use Paqtcom\Simplicate\Model\RestResultJournals;
use Paqtcom\Simplicate\Model\RestResultLeave;
use Paqtcom\Simplicate\Model\RestResultLeaveBalances;
use Paqtcom\Simplicate\Model\RestResultLeaveMultiple;
use Paqtcom\Simplicate\Model\RestResultLeaveType;
use Paqtcom\Simplicate\Model\RestResultLeaveTypes;
use Paqtcom\Simplicate\Model\RestResultLog;
use Paqtcom\Simplicate\Model\RestResultLogs;
use Paqtcom\Simplicate\Model\RestResultMerger;
use Paqtcom\Simplicate\Model\RestResultMergerCompare;
use Paqtcom\Simplicate\Model\RestResultMileage;
use Paqtcom\Simplicate\Model\RestResultMileageList;
use Paqtcom\Simplicate\Model\RestResultMyOrganizationProfile;
use Paqtcom\Simplicate\Model\RestResultMyOrganizationProfiles;
use Paqtcom\Simplicate\Model\RestResultOrganization;
use Paqtcom\Simplicate\Model\RestResultOrganizations;
use Paqtcom\Simplicate\Model\RestResultOrganizationSize;
use Paqtcom\Simplicate\Model\RestResultOrganizationSizes;
use Paqtcom\Simplicate\Model\RestResultPayment;
use Paqtcom\Simplicate\Model\RestResultPayments;
use Paqtcom\Simplicate\Model\RestResultPaymentTerm;
use Paqtcom\Simplicate\Model\RestResultPaymentTerms;
use Paqtcom\Simplicate\Model\RestResultPerson;
use Paqtcom\Simplicate\Model\RestResultPersons;
use Paqtcom\Simplicate\Model\RestResultProject;
use Paqtcom\Simplicate\Model\RestResultProjectAssignment;
use Paqtcom\Simplicate\Model\RestResultProjectAssignmentbudget;
use Paqtcom\Simplicate\Model\RestResultProjectAssignments;
use Paqtcom\Simplicate\Model\RestResultProjectAssignmentStatus;
use Paqtcom\Simplicate\Model\RestResultProjectAssignmentStatuses;
use Paqtcom\Simplicate\Model\RestResultProjectEmployee;
use Paqtcom\Simplicate\Model\RestResultProjectEmployees;
use Paqtcom\Simplicate\Model\RestResultProjects;
use Paqtcom\Simplicate\Model\RestResultProjectService;
use Paqtcom\Simplicate\Model\RestResultProjectServices;
use Paqtcom\Simplicate\Model\RestResultProjectStatus;
use Paqtcom\Simplicate\Model\RestResultProjectStatusses;
use Paqtcom\Simplicate\Model\RestResultProposition;
use Paqtcom\Simplicate\Model\RestResultPropositions;
use Paqtcom\Simplicate\Model\RestResultPurchase;
use Paqtcom\Simplicate\Model\RestResultPurchases;
use Paqtcom\Simplicate\Model\RestResultPurchaseType;
use Paqtcom\Simplicate\Model\RestResultPurchaseTypes;
use Paqtcom\Simplicate\Model\RestResultQuote;
use Paqtcom\Simplicate\Model\RestResultQuotes;
use Paqtcom\Simplicate\Model\RestResultQuoteStatus;
use Paqtcom\Simplicate\Model\RestResultQuoteStatuses;
use Paqtcom\Simplicate\Model\RestResultQuoteTemplate;
use Paqtcom\Simplicate\Model\RestResultQuoteTemplates;
use Paqtcom\Simplicate\Model\RestResultRelationType;
use Paqtcom\Simplicate\Model\RestResultRelationTypes;
use Paqtcom\Simplicate\Model\RestResultReminderSet;
use Paqtcom\Simplicate\Model\RestResultReminderSets;
use Paqtcom\Simplicate\Model\RestResultReminderTemplate;
use Paqtcom\Simplicate\Model\RestResultReminderTemplates;
use Paqtcom\Simplicate\Model\RestResultRevenueGroup;
use Paqtcom\Simplicate\Model\RestResultRevenueGroups;
use Paqtcom\Simplicate\Model\RestResultReverseInvoice;
use Paqtcom\Simplicate\Model\RestResultReverseInvoices;
use Paqtcom\Simplicate\Model\RestResultSale;
use Paqtcom\Simplicate\Model\RestResultSales;
use Paqtcom\Simplicate\Model\RestResultSalesProgress;
use Paqtcom\Simplicate\Model\RestResultSalesProgresses;
use Paqtcom\Simplicate\Model\RestResultSalesProgressHistories;
use Paqtcom\Simplicate\Model\RestResultSalesProgressHistory;
use Paqtcom\Simplicate\Model\RestResultSalesReason;
use Paqtcom\Simplicate\Model\RestResultSalesReasons;
use Paqtcom\Simplicate\Model\RestResultSalesService;
use Paqtcom\Simplicate\Model\RestResultSalesServices;
use Paqtcom\Simplicate\Model\RestResultSalesSource;
use Paqtcom\Simplicate\Model\RestResultSalesSources;
use Paqtcom\Simplicate\Model\RestResultSalesStatus;
use Paqtcom\Simplicate\Model\RestResultSalesStatusses;
use Paqtcom\Simplicate\Model\RestResultService;
use Paqtcom\Simplicate\Model\RestResultServiceGroup;
use Paqtcom\Simplicate\Model\RestResultServiceGroups;
use Paqtcom\Simplicate\Model\RestResultServices;
use Paqtcom\Simplicate\Model\RestResultSetting;
use Paqtcom\Simplicate\Model\RestResultSettings;
use Paqtcom\Simplicate\Model\RestResultSharedItem;
use Paqtcom\Simplicate\Model\RestResultSharedItems;
use Paqtcom\Simplicate\Model\RestResultTask;
use Paqtcom\Simplicate\Model\RestResultTasks;
use Paqtcom\Simplicate\Model\RestResultTeam;
use Paqtcom\Simplicate\Model\RestResultTeams;
use Paqtcom\Simplicate\Model\RestResultTimelineMessage;
use Paqtcom\Simplicate\Model\RestResultTimelineMessages;
use Paqtcom\Simplicate\Model\RestResultTimelineMessageType;
use Paqtcom\Simplicate\Model\RestResultTimelineMessageTypes;
use Paqtcom\Simplicate\Model\RestResultTimer;
use Paqtcom\Simplicate\Model\RestResultTimers;
use Paqtcom\Simplicate\Model\RestResultTimetable;
use Paqtcom\Simplicate\Model\RestResultTimetables;
use Paqtcom\Simplicate\Model\RestResultVatClass;
use Paqtcom\Simplicate\Model\RestResultVatClasses;
use Paqtcom\Simplicate\Model\RestResultWorkflow;
use Paqtcom\Simplicate\Model\RestResultWorkflowItem;
use Paqtcom\Simplicate\Model\RestResultWorkflowItems;
use Paqtcom\Simplicate\Model\RestResultWorkflowItemType;
use Paqtcom\Simplicate\Model\RestResultWorkflowItemTypes;
use Paqtcom\Simplicate\Model\RestResultWorkflows;
use Paqtcom\Simplicate\Model\ResultMergerMerge;
use Paqtcom\Simplicate\Model\ResultPostMergerCompare;
use Paqtcom\Simplicate\Model\RevenueGroup;
use Paqtcom\Simplicate\Model\ReverseInvoice;
use Paqtcom\Simplicate\Model\ReviewByWeekMetaData;
use Paqtcom\Simplicate\Model\Right;
use Paqtcom\Simplicate\Model\Rrule;
use Paqtcom\Simplicate\Model\Sales;
use Paqtcom\Simplicate\Model\SalesProgress;
use Paqtcom\Simplicate\Model\SalesProgressHistory;
use Paqtcom\Simplicate\Model\SalesReason;
use Paqtcom\Simplicate\Model\SalesService;
use Paqtcom\Simplicate\Model\SalesServiceCostType;
use Paqtcom\Simplicate\Model\SalesServiceHoursType;
use Paqtcom\Simplicate\Model\SalesSource;
use Paqtcom\Simplicate\Model\SalesStatus;
use Paqtcom\Simplicate\Model\SbiCode;
use Paqtcom\Simplicate\Model\SeparateInvoiceRecipient;
use Paqtcom\Simplicate\Model\Service;
use Paqtcom\Simplicate\Model\ServiceCostType;
use Paqtcom\Simplicate\Model\ServiceGroup;
use Paqtcom\Simplicate\Model\Setting;
use Paqtcom\Simplicate\Model\SubmissionStatus;
use Paqtcom\Simplicate\Model\Submit;
use Paqtcom\Simplicate\Model\SubscriptionCycle;
use Paqtcom\Simplicate\Model\Task;
use Paqtcom\Simplicate\Model\Team;
use Paqtcom\Simplicate\Model\Timer;
use Paqtcom\Simplicate\Model\TimesheetRow;
use Paqtcom\Simplicate\Model\Timetable;
use Paqtcom\Simplicate\Model\TimetableWeek;
use Paqtcom\Simplicate\Model\TimetableWeekDay;
use Paqtcom\Simplicate\Model\Timezone;
use Paqtcom\Simplicate\Model\User;
use Paqtcom\Simplicate\Model\VatClass;
use Paqtcom\Simplicate\Model\Workflow;
use Paqtcom\Simplicate\Model\WorkflowItem;
use Paqtcom\Simplicate\Model\WorkflowItemType;
use Paqtcom\Simplicate\Runtime\Normalizer\CheckArray;
use Paqtcom\Simplicate\Runtime\Normalizer\ReferenceNormalizer;
use Paqtcom\Simplicate\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class JaneObjectNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    protected array $normalizers = [
        Feature::class => \Paqtcom\Simplicate\Normalizer\FeatureNormalizer::class, Setting::class => \Paqtcom\Simplicate\Normalizer\SettingNormalizer::class, App::class => \Paqtcom\Simplicate\Normalizer\AppNormalizer::class, Log::class => \Paqtcom\Simplicate\Normalizer\LogNormalizer::class, ServiceGroup::class => \Paqtcom\Simplicate\Normalizer\ServiceGroupNormalizer::class, BaseSetting::class => \Paqtcom\Simplicate\Normalizer\BaseSettingNormalizer::class, Expense::class => \Paqtcom\Simplicate\Normalizer\ExpenseNormalizer::class, ExpenseAttachment::class => \Paqtcom\Simplicate\Normalizer\ExpenseAttachmentNormalizer::class, PostExpense::class => \Paqtcom\Simplicate\Normalizer\PostExpenseNormalizer::class, Accountancy::class => \Paqtcom\Simplicate\Normalizer\AccountancyNormalizer::class, Address::class => \Paqtcom\Simplicate\Normalizer\AddressNormalizer::class, Administration::class => \Paqtcom\Simplicate\Normalizer\AdministrationNormalizer::class, ContactPerson::class => \Paqtcom\Simplicate\Normalizer\ContactPersonNormalizer::class, Country::class => \Paqtcom\Simplicate\Normalizer\CountryNormalizer::class, CustomerGroup::class => \Paqtcom\Simplicate\Normalizer\CustomerGroupNormalizer::class, Debtor::class => \Paqtcom\Simplicate\Normalizer\DebtorNormalizer::class, DebtorList::class => \Paqtcom\Simplicate\Normalizer\DebtorListNormalizer::class, ExternalList::class => \Paqtcom\Simplicate\Normalizer\ExternalListNormalizer::class, ExternalListTag::class => \Paqtcom\Simplicate\Normalizer\ExternalListTagNormalizer::class, Gender::class => \Paqtcom\Simplicate\Normalizer\GenderNormalizer::class, GetAddress::class => \Paqtcom\Simplicate\Normalizer\GetAddressNormalizer::class, GetBasicPersonSimple::class => \Paqtcom\Simplicate\Normalizer\GetBasicPersonSimpleNormalizer::class, GetContactPerson::class => \Paqtcom\Simplicate\Normalizer\GetContactPersonNormalizer::class, GetContactSimple::class => \Paqtcom\Simplicate\Normalizer\GetContactSimpleNormalizer::class, GetDebtor::class => \Paqtcom\Simplicate\Normalizer\GetDebtorNormalizer::class, GetInterest::class => \Paqtcom\Simplicate\Normalizer\GetInterestNormalizer::class, GetMyOrganizationProfileSimple::class => \Paqtcom\Simplicate\Normalizer\GetMyOrganizationProfileSimpleNormalizer::class, GetOrganization::class => \Paqtcom\Simplicate\Normalizer\GetOrganizationNormalizer::class, GetOrganizationDebtorSimple::class => \Paqtcom\Simplicate\Normalizer\GetOrganizationDebtorSimpleNormalizer::class, GetOrganizationSimple::class => \Paqtcom\Simplicate\Normalizer\GetOrganizationSimpleNormalizer::class, GetPerson::class => \Paqtcom\Simplicate\Normalizer\GetPersonNormalizer::class, GetPersonDebtorSimple::class => \Paqtcom\Simplicate\Normalizer\GetPersonDebtorSimpleNormalizer::class, GetPersonSimple::class => \Paqtcom\Simplicate\Normalizer\GetPersonSimpleNormalizer::class, Industry::class => \Paqtcom\Simplicate\Normalizer\IndustryNormalizer::class, Interest::class => \Paqtcom\Simplicate\Normalizer\InterestNormalizer::class, MailingList::class => \Paqtcom\Simplicate\Normalizer\MailingListNormalizer::class, MyOrganizationProfile::class => \Paqtcom\Simplicate\Normalizer\MyOrganizationProfileNormalizer::class, Organization::class => \Paqtcom\Simplicate\Normalizer\OrganizationNormalizer::class, OrganizationContact::class => \Paqtcom\Simplicate\Normalizer\OrganizationContactNormalizer::class, OrganizationSize::class => \Paqtcom\Simplicate\Normalizer\OrganizationSizeNormalizer::class, Person::class => \Paqtcom\Simplicate\Normalizer\PersonNormalizer::class, PersonContact::class => \Paqtcom\Simplicate\Normalizer\PersonContactNormalizer::class, PersonMailingList::class => \Paqtcom\Simplicate\Normalizer\PersonMailingListNormalizer::class, PostAddress::class => \Paqtcom\Simplicate\Normalizer\PostAddressNormalizer::class, PostContactOrganizationFk::class => \Paqtcom\Simplicate\Normalizer\PostContactOrganizationFkNormalizer::class, PostContactPerson::class => \Paqtcom\Simplicate\Normalizer\PostContactPersonNormalizer::class, PostContactPersonFk::class => \Paqtcom\Simplicate\Normalizer\PostContactPersonFkNormalizer::class, PostContactPersonProperties::class => \Paqtcom\Simplicate\Normalizer\PostContactPersonPropertiesNormalizer::class, PostDebtor::class => \Paqtcom\Simplicate\Normalizer\PostDebtorNormalizer::class, PostInterest::class => \Paqtcom\Simplicate\Normalizer\PostInterestNormalizer::class, PostOrganization::class => \Paqtcom\Simplicate\Normalizer\PostOrganizationNormalizer::class, PostOrganizationFk::class => \Paqtcom\Simplicate\Normalizer\PostOrganizationFkNormalizer::class, PostPerson::class => \Paqtcom\Simplicate\Normalizer\PostPersonNormalizer::class, PostTeam::class => \Paqtcom\Simplicate\Normalizer\PostTeamNormalizer::class, PutContactPerson::class => \Paqtcom\Simplicate\Normalizer\PutContactPersonNormalizer::class, RelationType::class => \Paqtcom\Simplicate\Normalizer\RelationTypeNormalizer::class, SbiCode::class => \Paqtcom\Simplicate\Normalizer\SbiCodeNormalizer::class, Timezone::class => \Paqtcom\Simplicate\Normalizer\TimezoneNormalizer::class, CustomField::class => \Paqtcom\Simplicate\Normalizer\CustomFieldNormalizer::class, CustomFieldGroup::class => \Paqtcom\Simplicate\Normalizer\CustomFieldGroupNormalizer::class, CustomFieldModel::class => \Paqtcom\Simplicate\Normalizer\CustomFieldModelNormalizer::class, CustomFieldOption::class => \Paqtcom\Simplicate\Normalizer\CustomFieldOptionNormalizer::class, CustomFieldType::class => \Paqtcom\Simplicate\Normalizer\CustomFieldTypeNormalizer::class, GetCustomField::class => \Paqtcom\Simplicate\Normalizer\GetCustomFieldNormalizer::class, PostCustomFieldValue::class => \Paqtcom\Simplicate\Normalizer\PostCustomFieldValueNormalizer::class, Document::class => \Paqtcom\Simplicate\Normalizer\DocumentNormalizer::class, DocumentType::class => \Paqtcom\Simplicate\Normalizer\DocumentTypeNormalizer::class, DocumentTypeSimple::class => \Paqtcom\Simplicate\Normalizer\DocumentTypeSimpleNormalizer::class, GetDocument::class => \Paqtcom\Simplicate\Normalizer\GetDocumentNormalizer::class, GetDocumentType::class => \Paqtcom\Simplicate\Normalizer\GetDocumentTypeNormalizer::class, PostDocument::class => \Paqtcom\Simplicate\Normalizer\PostDocumentNormalizer::class, PostDocumentLinkedTo::class => \Paqtcom\Simplicate\Normalizer\PostDocumentLinkedToNormalizer::class, PostQuoteTemplate::class => \Paqtcom\Simplicate\Normalizer\PostQuoteTemplateNormalizer::class, PutDocument::class => \Paqtcom\Simplicate\Normalizer\PutDocumentNormalizer::class, QuoteTemplate::class => \Paqtcom\Simplicate\Normalizer\QuoteTemplateNormalizer::class, Filter::class => \Paqtcom\Simplicate\Normalizer\FilterNormalizer::class, Approval::class => \Paqtcom\Simplicate\Normalizer\ApprovalNormalizer::class, ApprovalStatus::class => \Paqtcom\Simplicate\Normalizer\ApprovalStatusNormalizer::class, BaseHours::class => \Paqtcom\Simplicate\Normalizer\BaseHoursNormalizer::class, CalendarItem::class => \Paqtcom\Simplicate\Normalizer\CalendarItemNormalizer::class, Correction::class => \Paqtcom\Simplicate\Normalizer\CorrectionNormalizer::class, DateTimeRange::class => \Paqtcom\Simplicate\Normalizer\DateTimeRangeNormalizer::class, ExternalItemMetadata::class => \Paqtcom\Simplicate\Normalizer\ExternalItemMetadataNormalizer::class, ExternalItemMetadataConfiguration::class => \Paqtcom\Simplicate\Normalizer\ExternalItemMetadataConfigurationNormalizer::class, GetApproval::class => \Paqtcom\Simplicate\Normalizer\GetApprovalNormalizer::class, GetApprovalStatus::class => \Paqtcom\Simplicate\Normalizer\GetApprovalStatusNormalizer::class, GetHours::class => \Paqtcom\Simplicate\Normalizer\GetHoursNormalizer::class, GetHoursHoursProjectService::class => \Paqtcom\Simplicate\Normalizer\GetHoursHoursProjectServiceNormalizer::class, GetHoursProjectService::class => \Paqtcom\Simplicate\Normalizer\GetHoursProjectServiceNormalizer::class, GetHoursSimple::class => \Paqtcom\Simplicate\Normalizer\GetHoursSimpleNormalizer::class, GetHoursType::class => \Paqtcom\Simplicate\Normalizer\GetHoursTypeNormalizer::class, GetLeaveType::class => \Paqtcom\Simplicate\Normalizer\GetLeaveTypeNormalizer::class, GetProjectServiceCostType::class => \Paqtcom\Simplicate\Normalizer\GetProjectServiceCostTypeNormalizer::class, GetProjectServiceHoursType::class => \Paqtcom\Simplicate\Normalizer\GetProjectServiceHoursTypeNormalizer::class, GetSalesServiceCostType::class => \Paqtcom\Simplicate\Normalizer\GetSalesServiceCostTypeNormalizer::class, GetSalesServiceHoursType::class => \Paqtcom\Simplicate\Normalizer\GetSalesServiceHoursTypeNormalizer::class, GetServiceCostType::class => \Paqtcom\Simplicate\Normalizer\GetServiceCostTypeNormalizer::class, Hours::class => \Paqtcom\Simplicate\Normalizer\HoursNormalizer::class, HoursType::class => \Paqtcom\Simplicate\Normalizer\HoursTypeNormalizer::class, LeaveStatus::class => \Paqtcom\Simplicate\Normalizer\LeaveStatusNormalizer::class, MileageType::class => \Paqtcom\Simplicate\Normalizer\MileageTypeNormalizer::class, PostApproval::class => \Paqtcom\Simplicate\Normalizer\PostApprovalNormalizer::class, PostCalendarItem::class => \Paqtcom\Simplicate\Normalizer\PostCalendarItemNormalizer::class, PostHours::class => \Paqtcom\Simplicate\Normalizer\PostHoursNormalizer::class, PostHoursType::class => \Paqtcom\Simplicate\Normalizer\PostHoursTypeNormalizer::class, PostProjectServiceHoursType::class => \Paqtcom\Simplicate\Normalizer\PostProjectServiceHoursTypeNormalizer::class, PostSubmission::class => \Paqtcom\Simplicate\Normalizer\PostSubmissionNormalizer::class, PostTimesheetRow::class => \Paqtcom\Simplicate\Normalizer\PostTimesheetRowNormalizer::class, ProjectServiceCostType::class => \Paqtcom\Simplicate\Normalizer\ProjectServiceCostTypeNormalizer::class, ProjectServiceHoursType::class => \Paqtcom\Simplicate\Normalizer\ProjectServiceHoursTypeNormalizer::class, Recurrence::class => \Paqtcom\Simplicate\Normalizer\RecurrenceNormalizer::class, Rrule::class => \Paqtcom\Simplicate\Normalizer\RruleNormalizer::class, SalesServiceCostType::class => \Paqtcom\Simplicate\Normalizer\SalesServiceCostTypeNormalizer::class, SalesServiceHoursType::class => \Paqtcom\Simplicate\Normalizer\SalesServiceHoursTypeNormalizer::class, ServiceCostType::class => \Paqtcom\Simplicate\Normalizer\ServiceCostTypeNormalizer::class, SubmissionStatus::class => \Paqtcom\Simplicate\Normalizer\SubmissionStatusNormalizer::class, Submit::class => \Paqtcom\Simplicate\Normalizer\SubmitNormalizer::class, GetTimesheetRow::class => \Paqtcom\Simplicate\Normalizer\GetTimesheetRowNormalizer::class, GetTimesheetRowItemtype::class => \Paqtcom\Simplicate\Normalizer\GetTimesheetRowItemtypeNormalizer::class, GetTimesheetRowOrganizationRelation::class => \Paqtcom\Simplicate\Normalizer\GetTimesheetRowOrganizationRelationNormalizer::class, GetTimesheetRowPersonRelation::class => \Paqtcom\Simplicate\Normalizer\GetTimesheetRowPersonRelationNormalizer::class, GetTimesheetRowProject::class => \Paqtcom\Simplicate\Normalizer\GetTimesheetRowProjectNormalizer::class, GetTimesheetRowProjectService::class => \Paqtcom\Simplicate\Normalizer\GetTimesheetRowProjectServiceNormalizer::class, TimesheetRow::class => \Paqtcom\Simplicate\Normalizer\TimesheetRowNormalizer::class, Absence::class => \Paqtcom\Simplicate\Normalizer\AbsenceNormalizer::class, AbsenceType::class => \Paqtcom\Simplicate\Normalizer\AbsenceTypeNormalizer::class, CivilStatus::class => \Paqtcom\Simplicate\Normalizer\CivilStatusNormalizer::class, Contract::class => \Paqtcom\Simplicate\Normalizer\ContractNormalizer::class, ContractType::class => \Paqtcom\Simplicate\Normalizer\ContractTypeNormalizer::class, Employee::class => \Paqtcom\Simplicate\Normalizer\EmployeeNormalizer::class, EmployeeStatus::class => \Paqtcom\Simplicate\Normalizer\EmployeeStatusNormalizer::class, EmployeeType::class => \Paqtcom\Simplicate\Normalizer\EmployeeTypeNormalizer::class, EmploymentType::class => \Paqtcom\Simplicate\Normalizer\EmploymentTypeNormalizer::class, GetAbsence::class => \Paqtcom\Simplicate\Normalizer\GetAbsenceNormalizer::class, GetAbsenceType::class => \Paqtcom\Simplicate\Normalizer\GetAbsenceTypeNormalizer::class, GetCivilStatus::class => \Paqtcom\Simplicate\Normalizer\GetCivilStatusNormalizer::class, GetContract::class => \Paqtcom\Simplicate\Normalizer\GetContractNormalizer::class, GetEmployee::class => \Paqtcom\Simplicate\Normalizer\GetEmployeeNormalizer::class, GetEmployeeSimple::class => \Paqtcom\Simplicate\Normalizer\GetEmployeeSimpleNormalizer::class, GetLeave::class => \Paqtcom\Simplicate\Normalizer\GetLeaveNormalizer::class, HrmGetLeaveType::class => \Paqtcom\Simplicate\Normalizer\HrmGetLeaveTypeNormalizer::class, GetTeam::class => \Paqtcom\Simplicate\Normalizer\GetTeamNormalizer::class, GetTeamSimple::class => \Paqtcom\Simplicate\Normalizer\GetTeamSimpleNormalizer::class, GetTimetable::class => \Paqtcom\Simplicate\Normalizer\GetTimetableNormalizer::class, Leave::class => \Paqtcom\Simplicate\Normalizer\LeaveNormalizer::class, LeaveBalance::class => \Paqtcom\Simplicate\Normalizer\LeaveBalanceNormalizer::class, LeaveType::class => \Paqtcom\Simplicate\Normalizer\LeaveTypeNormalizer::class, PostAbsence::class => \Paqtcom\Simplicate\Normalizer\PostAbsenceNormalizer::class, PostEmployee::class => \Paqtcom\Simplicate\Normalizer\PostEmployeeNormalizer::class, PostEmployeeFk::class => \Paqtcom\Simplicate\Normalizer\PostEmployeeFkNormalizer::class, PostEmployeeStatusFk::class => \Paqtcom\Simplicate\Normalizer\PostEmployeeStatusFkNormalizer::class, PostLeave::class => \Paqtcom\Simplicate\Normalizer\PostLeaveNormalizer::class, HrmPostTeam::class => \Paqtcom\Simplicate\Normalizer\HrmPostTeamNormalizer::class, PostTimetable::class => \Paqtcom\Simplicate\Normalizer\PostTimetableNormalizer::class, PutEmployee::class => \Paqtcom\Simplicate\Normalizer\PutEmployeeNormalizer::class, PutTimetable::class => \Paqtcom\Simplicate\Normalizer\PutTimetableNormalizer::class, Team::class => \Paqtcom\Simplicate\Normalizer\TeamNormalizer::class, Timetable::class => \Paqtcom\Simplicate\Normalizer\TimetableNormalizer::class, TimetableWeek::class => \Paqtcom\Simplicate\Normalizer\TimetableWeekNormalizer::class, TimetableWeekDay::class => \Paqtcom\Simplicate\Normalizer\TimetableWeekDayNormalizer::class, EmailAttachment::class => \Paqtcom\Simplicate\Normalizer\EmailAttachmentNormalizer::class, EmailMessage::class => \Paqtcom\Simplicate\Normalizer\EmailMessageNormalizer::class, Inbox::class => \Paqtcom\Simplicate\Normalizer\InboxNormalizer::class, GetInvoice::class => \Paqtcom\Simplicate\Normalizer\GetInvoiceNormalizer::class, GetInvoiceLine::class => \Paqtcom\Simplicate\Normalizer\GetInvoiceLineNormalizer::class, GetInvoiceReminder::class => \Paqtcom\Simplicate\Normalizer\GetInvoiceReminderNormalizer::class, GetInvoiceSimple::class => \Paqtcom\Simplicate\Normalizer\GetInvoiceSimpleNormalizer::class, GetPayment::class => \Paqtcom\Simplicate\Normalizer\GetPaymentNormalizer::class, GetPaymentTerm::class => \Paqtcom\Simplicate\Normalizer\GetPaymentTermNormalizer::class, GetProposition::class => \Paqtcom\Simplicate\Normalizer\GetPropositionNormalizer::class, GetReminderSet::class => \Paqtcom\Simplicate\Normalizer\GetReminderSetNormalizer::class, GetReminderSetSimple::class => \Paqtcom\Simplicate\Normalizer\GetReminderSetSimpleNormalizer::class, Invoice::class => \Paqtcom\Simplicate\Normalizer\InvoiceNormalizer::class, InvoiceLine::class => \Paqtcom\Simplicate\Normalizer\InvoiceLineNormalizer::class, InvoiceStatus::class => \Paqtcom\Simplicate\Normalizer\InvoiceStatusNormalizer::class, InvoiceTemplate::class => \Paqtcom\Simplicate\Normalizer\InvoiceTemplateNormalizer::class, Journal::class => \Paqtcom\Simplicate\Normalizer\JournalNormalizer::class, JournalLine::class => \Paqtcom\Simplicate\Normalizer\JournalLineNormalizer::class, JournalVat::class => \Paqtcom\Simplicate\Normalizer\JournalVatNormalizer::class, Payment::class => \Paqtcom\Simplicate\Normalizer\PaymentNormalizer::class, PaymentTerm::class => \Paqtcom\Simplicate\Normalizer\PaymentTermNormalizer::class, PostInvoice::class => \Paqtcom\Simplicate\Normalizer\PostInvoiceNormalizer::class, PostInvoiceLine::class => \Paqtcom\Simplicate\Normalizer\PostInvoiceLineNormalizer::class, PostVatClassFk::class => \Paqtcom\Simplicate\Normalizer\PostVatClassFkNormalizer::class, ReminderSet::class => \Paqtcom\Simplicate\Normalizer\ReminderSetNormalizer::class, ReminderSetTemplate::class => \Paqtcom\Simplicate\Normalizer\ReminderSetTemplateNormalizer::class, ReminderTemplate::class => \Paqtcom\Simplicate\Normalizer\ReminderTemplateNormalizer::class, SubscriptionCycle::class => \Paqtcom\Simplicate\Normalizer\SubscriptionCycleNormalizer::class, VatClass::class => \Paqtcom\Simplicate\Normalizer\VatClassNormalizer::class, PostMerger::class => \Paqtcom\Simplicate\Normalizer\PostMergerNormalizer::class, PostMergerCompare::class => \Paqtcom\Simplicate\Normalizer\PostMergerCompareNormalizer::class, ResultMergerMerge::class => \Paqtcom\Simplicate\Normalizer\ResultMergerMergeNormalizer::class, ResultPostMergerCompare::class => \Paqtcom\Simplicate\Normalizer\ResultPostMergerCompareNormalizer::class, MetaData::class => \Paqtcom\Simplicate\Normalizer\MetaDataNormalizer::class, GetMileage::class => \Paqtcom\Simplicate\Normalizer\GetMileageNormalizer::class, GetMileageSimple::class => \Paqtcom\Simplicate\Normalizer\GetMileageSimpleNormalizer::class, Mileage::class => \Paqtcom\Simplicate\Normalizer\MileageNormalizer::class, PostMileage::class => \Paqtcom\Simplicate\Normalizer\PostMileageNormalizer::class, PutMileage::class => \Paqtcom\Simplicate\Normalizer\PutMileageNormalizer::class, PkRestResult::class => \Paqtcom\Simplicate\Normalizer\PkRestResultNormalizer::class, Assignment::class => \Paqtcom\Simplicate\Normalizer\AssignmentNormalizer::class, AssignmentBudget::class => \Paqtcom\Simplicate\Normalizer\AssignmentBudgetNormalizer::class, AssignmentBudgetInfo::class => \Paqtcom\Simplicate\Normalizer\AssignmentBudgetInfoNormalizer::class, AssignmentBudgetInfoFuturePast::class => \Paqtcom\Simplicate\Normalizer\AssignmentBudgetInfoFuturePastNormalizer::class, AssignmentBudgetInfoMetaData::class => \Paqtcom\Simplicate\Normalizer\AssignmentBudgetInfoMetaDataNormalizer::class, AssignmentStatus::class => \Paqtcom\Simplicate\Normalizer\AssignmentStatusNormalizer::class, Budget::class => \Paqtcom\Simplicate\Normalizer\BudgetNormalizer::class, BudgetCosts::class => \Paqtcom\Simplicate\Normalizer\BudgetCostsNormalizer::class, BudgetHours::class => \Paqtcom\Simplicate\Normalizer\BudgetHoursNormalizer::class, BudgetTotal::class => \Paqtcom\Simplicate\Normalizer\BudgetTotalNormalizer::class, GetAssignment::class => \Paqtcom\Simplicate\Normalizer\GetAssignmentNormalizer::class, GetAssignmentSimple::class => \Paqtcom\Simplicate\Normalizer\GetAssignmentSimpleNormalizer::class, GetAssignmentStatus::class => \Paqtcom\Simplicate\Normalizer\GetAssignmentStatusNormalizer::class, GetProject::class => \Paqtcom\Simplicate\Normalizer\GetProjectNormalizer::class, GetProjectService::class => \Paqtcom\Simplicate\Normalizer\GetProjectServiceNormalizer::class, GetProjectServiceSimple::class => \Paqtcom\Simplicate\Normalizer\GetProjectServiceSimpleNormalizer::class, GetProjectSimple::class => \Paqtcom\Simplicate\Normalizer\GetProjectSimpleNormalizer::class, GetPurchaseType::class => \Paqtcom\Simplicate\Normalizer\GetPurchaseTypeNormalizer::class, PostAssignment::class => \Paqtcom\Simplicate\Normalizer\PostAssignmentNormalizer::class, PostProject::class => \Paqtcom\Simplicate\Normalizer\PostProjectNormalizer::class, PostProjectService::class => \Paqtcom\Simplicate\Normalizer\PostProjectServiceNormalizer::class, PostPurchaseType::class => \Paqtcom\Simplicate\Normalizer\PostPurchaseTypeNormalizer::class, Project::class => \Paqtcom\Simplicate\Normalizer\ProjectNormalizer::class, ProjectAssignmentDeleteResultRest::class => \Paqtcom\Simplicate\Normalizer\ProjectAssignmentDeleteResultRestNormalizer::class, ProjectEmployee::class => \Paqtcom\Simplicate\Normalizer\ProjectEmployeeNormalizer::class, ProjectManager::class => \Paqtcom\Simplicate\Normalizer\ProjectManagerNormalizer::class, ProjectStatus::class => \Paqtcom\Simplicate\Normalizer\ProjectStatusNormalizer::class, Purchase::class => \Paqtcom\Simplicate\Normalizer\PurchaseNormalizer::class, PurchaseType::class => \Paqtcom\Simplicate\Normalizer\PurchaseTypeNormalizer::class, PutAssignment::class => \Paqtcom\Simplicate\Normalizer\PutAssignmentNormalizer::class, PutProjectService::class => \Paqtcom\Simplicate\Normalizer\PutProjectServiceNormalizer::class, ReverseInvoice::class => \Paqtcom\Simplicate\Normalizer\ReverseInvoiceNormalizer::class, AppReceiverSetting::class => \Paqtcom\Simplicate\Normalizer\AppReceiverSettingNormalizer::class, AppReceivers::class => \Paqtcom\Simplicate\Normalizer\AppReceiversNormalizer::class, RestBatchValidationError::class => \Paqtcom\Simplicate\Normalizer\RestBatchValidationErrorNormalizer::class, RestError::class => \Paqtcom\Simplicate\Normalizer\RestErrorNormalizer::class, RestResultApps::class => \Paqtcom\Simplicate\Normalizer\RestResultAppsNormalizer::class, RestResultApp::class => \Paqtcom\Simplicate\Normalizer\RestResultAppNormalizer::class, RestResultLogs::class => \Paqtcom\Simplicate\Normalizer\RestResultLogsNormalizer::class, RestResultLog::class => \Paqtcom\Simplicate\Normalizer\RestResultLogNormalizer::class, RestResultCustomFieldGroups::class => \Paqtcom\Simplicate\Normalizer\RestResultCustomFieldGroupsNormalizer::class, RestResultCustomFieldGroup::class => \Paqtcom\Simplicate\Normalizer\RestResultCustomFieldGroupNormalizer::class, RestResultCustomFields::class => \Paqtcom\Simplicate\Normalizer\RestResultCustomFieldsNormalizer::class, RestResultCustomField::class => \Paqtcom\Simplicate\Normalizer\RestResultCustomFieldNormalizer::class, RestResultServiceGroups::class => \Paqtcom\Simplicate\Normalizer\RestResultServiceGroupsNormalizer::class, RestResultServiceGroup::class => \Paqtcom\Simplicate\Normalizer\RestResultServiceGroupNormalizer::class, RestResultSettings::class => \Paqtcom\Simplicate\Normalizer\RestResultSettingsNormalizer::class, RestResultSetting::class => \Paqtcom\Simplicate\Normalizer\RestResultSettingNormalizer::class, RestResultAdministrations::class => \Paqtcom\Simplicate\Normalizer\RestResultAdministrationsNormalizer::class, RestResultAdministration::class => \Paqtcom\Simplicate\Normalizer\RestResultAdministrationNormalizer::class, RestResultMyOrganizationProfiles::class => \Paqtcom\Simplicate\Normalizer\RestResultMyOrganizationProfilesNormalizer::class, RestResultMyOrganizationProfile::class => \Paqtcom\Simplicate\Normalizer\RestResultMyOrganizationProfileNormalizer::class, RestResultContacts::class => \Paqtcom\Simplicate\Normalizer\RestResultContactsNormalizer::class, RestResultContact::class => \Paqtcom\Simplicate\Normalizer\RestResultContactNormalizer::class, RestResultOrganizations::class => \Paqtcom\Simplicate\Normalizer\RestResultOrganizationsNormalizer::class, RestResultOrganization::class => \Paqtcom\Simplicate\Normalizer\RestResultOrganizationNormalizer::class, RestResultPersons::class => \Paqtcom\Simplicate\Normalizer\RestResultPersonsNormalizer::class, RestResultPerson::class => \Paqtcom\Simplicate\Normalizer\RestResultPersonNormalizer::class, RestResultRelationTypes::class => \Paqtcom\Simplicate\Normalizer\RestResultRelationTypesNormalizer::class, RestResultRelationType::class => \Paqtcom\Simplicate\Normalizer\RestResultRelationTypeNormalizer::class, RestResultCountries::class => \Paqtcom\Simplicate\Normalizer\RestResultCountriesNormalizer::class, RestResultCountry::class => \Paqtcom\Simplicate\Normalizer\RestResultCountryNormalizer::class, RestResultGenders::class => \Paqtcom\Simplicate\Normalizer\RestResultGendersNormalizer::class, RestResultGender::class => \Paqtcom\Simplicate\Normalizer\RestResultGenderNormalizer::class, RestResultTimetables::class => \Paqtcom\Simplicate\Normalizer\RestResultTimetablesNormalizer::class, RestResultTimetable::class => \Paqtcom\Simplicate\Normalizer\RestResultTimetableNormalizer::class, RestResultContractTypes::class => \Paqtcom\Simplicate\Normalizer\RestResultContractTypesNormalizer::class, RestResultContractType::class => \Paqtcom\Simplicate\Normalizer\RestResultContractTypeNormalizer::class, RestResultEmploymentTypes::class => \Paqtcom\Simplicate\Normalizer\RestResultEmploymentTypesNormalizer::class, RestResultEmploymentType::class => \Paqtcom\Simplicate\Normalizer\RestResultEmploymentTypeNormalizer::class, RestResultEmployeeTypes::class => \Paqtcom\Simplicate\Normalizer\RestResultEmployeeTypesNormalizer::class, RestResultEmployeeType::class => \Paqtcom\Simplicate\Normalizer\RestResultEmployeeTypeNormalizer::class, RestResultCivilStatuses::class => \Paqtcom\Simplicate\Normalizer\RestResultCivilStatusesNormalizer::class, RestResultCivilStatus::class => \Paqtcom\Simplicate\Normalizer\RestResultCivilStatusNormalizer::class, RestResultOrganizationSizes::class => \Paqtcom\Simplicate\Normalizer\RestResultOrganizationSizesNormalizer::class, RestResultOrganizationSize::class => \Paqtcom\Simplicate\Normalizer\RestResultOrganizationSizeNormalizer::class, RestResultContracts::class => \Paqtcom\Simplicate\Normalizer\RestResultContractsNormalizer::class, RestResultContract::class => \Paqtcom\Simplicate\Normalizer\RestResultContractNormalizer::class, RestResultTeams::class => \Paqtcom\Simplicate\Normalizer\RestResultTeamsNormalizer::class, RestResultTeam::class => \Paqtcom\Simplicate\Normalizer\RestResultTeamNormalizer::class, RestResultIndustries::class => \Paqtcom\Simplicate\Normalizer\RestResultIndustriesNormalizer::class, RestResultIndustry::class => \Paqtcom\Simplicate\Normalizer\RestResultIndustryNormalizer::class, RestResultInterests::class => \Paqtcom\Simplicate\Normalizer\RestResultInterestsNormalizer::class, RestResultInterest::class => \Paqtcom\Simplicate\Normalizer\RestResultInterestNormalizer::class, RestResultEmployees::class => \Paqtcom\Simplicate\Normalizer\RestResultEmployeesNormalizer::class, RestResultEmployee::class => \Paqtcom\Simplicate\Normalizer\RestResultEmployeeNormalizer::class, RestResultInvoices::class => \Paqtcom\Simplicate\Normalizer\RestResultInvoicesNormalizer::class, RestResultInvoice::class => \Paqtcom\Simplicate\Normalizer\RestResultInvoiceNormalizer::class, RestResultInvoiceStatuses::class => \Paqtcom\Simplicate\Normalizer\RestResultInvoiceStatusesNormalizer::class, RestResultInvoiceStatus::class => \Paqtcom\Simplicate\Normalizer\RestResultInvoiceStatusNormalizer::class, RestResultJournals::class => \Paqtcom\Simplicate\Normalizer\RestResultJournalsNormalizer::class, RestResultJournal::class => \Paqtcom\Simplicate\Normalizer\RestResultJournalNormalizer::class, RestResultPayments::class => \Paqtcom\Simplicate\Normalizer\RestResultPaymentsNormalizer::class, RestResultPayment::class => \Paqtcom\Simplicate\Normalizer\RestResultPaymentNormalizer::class, RestResultPaymentTerms::class => \Paqtcom\Simplicate\Normalizer\RestResultPaymentTermsNormalizer::class, RestResultPaymentTerm::class => \Paqtcom\Simplicate\Normalizer\RestResultPaymentTermNormalizer::class, RestResultVatClasses::class => \Paqtcom\Simplicate\Normalizer\RestResultVatClassesNormalizer::class, RestResultVatClass::class => \Paqtcom\Simplicate\Normalizer\RestResultVatClassNormalizer::class, RestResultProjects::class => \Paqtcom\Simplicate\Normalizer\RestResultProjectsNormalizer::class, RestResultProject::class => \Paqtcom\Simplicate\Normalizer\RestResultProjectNormalizer::class, RestResultProjectEmployees::class => \Paqtcom\Simplicate\Normalizer\RestResultProjectEmployeesNormalizer::class, RestResultProjectEmployee::class => \Paqtcom\Simplicate\Normalizer\RestResultProjectEmployeeNormalizer::class, RestResultProjectStatusses::class => \Paqtcom\Simplicate\Normalizer\RestResultProjectStatussesNormalizer::class, RestResultProjectStatus::class => \Paqtcom\Simplicate\Normalizer\RestResultProjectStatusNormalizer::class, RestResultProjectServices::class => \Paqtcom\Simplicate\Normalizer\RestResultProjectServicesNormalizer::class, RestResultProjectService::class => \Paqtcom\Simplicate\Normalizer\RestResultProjectServiceNormalizer::class, RestResultPurchaseTypes::class => \Paqtcom\Simplicate\Normalizer\RestResultPurchaseTypesNormalizer::class, RestResultPurchaseType::class => \Paqtcom\Simplicate\Normalizer\RestResultPurchaseTypeNormalizer::class, RestResultServices::class => \Paqtcom\Simplicate\Normalizer\RestResultServicesNormalizer::class, RestResultService::class => \Paqtcom\Simplicate\Normalizer\RestResultServiceNormalizer::class, RestResultSalesServices::class => \Paqtcom\Simplicate\Normalizer\RestResultSalesServicesNormalizer::class, RestResultSalesService::class => \Paqtcom\Simplicate\Normalizer\RestResultSalesServiceNormalizer::class, RestResultDefaultServices::class => \Paqtcom\Simplicate\Normalizer\RestResultDefaultServicesNormalizer::class, RestResultDefaultService::class => \Paqtcom\Simplicate\Normalizer\RestResultDefaultServiceNormalizer::class, RestResultWorkflows::class => \Paqtcom\Simplicate\Normalizer\RestResultWorkflowsNormalizer::class, RestResultWorkflow::class => \Paqtcom\Simplicate\Normalizer\RestResultWorkflowNormalizer::class, RestResultWorkflowItems::class => \Paqtcom\Simplicate\Normalizer\RestResultWorkflowItemsNormalizer::class, RestResultWorkflowItem::class => \Paqtcom\Simplicate\Normalizer\RestResultWorkflowItemNormalizer::class, RestResultWorkflowItemTypes::class => \Paqtcom\Simplicate\Normalizer\RestResultWorkflowItemTypesNormalizer::class, RestResultWorkflowItemType::class => \Paqtcom\Simplicate\Normalizer\RestResultWorkflowItemTypeNormalizer::class, RestResultTasks::class => \Paqtcom\Simplicate\Normalizer\RestResultTasksNormalizer::class, RestResultTask::class => \Paqtcom\Simplicate\Normalizer\RestResultTaskNormalizer::class, RestResultSales::class => \Paqtcom\Simplicate\Normalizer\RestResultSalesNormalizer::class, RestResultSale::class => \Paqtcom\Simplicate\Normalizer\RestResultSaleNormalizer::class, RestResultRevenueGroups::class => \Paqtcom\Simplicate\Normalizer\RestResultRevenueGroupsNormalizer::class, RestResultRevenueGroup::class => \Paqtcom\Simplicate\Normalizer\RestResultRevenueGroupNormalizer::class, RestResultSalesProgresses::class => \Paqtcom\Simplicate\Normalizer\RestResultSalesProgressesNormalizer::class, RestResultSalesProgress::class => \Paqtcom\Simplicate\Normalizer\RestResultSalesProgressNormalizer::class, RestResultSalesSources::class => \Paqtcom\Simplicate\Normalizer\RestResultSalesSourcesNormalizer::class, RestResultSalesSource::class => \Paqtcom\Simplicate\Normalizer\RestResultSalesSourceNormalizer::class, RestResultSalesStatusses::class => \Paqtcom\Simplicate\Normalizer\RestResultSalesStatussesNormalizer::class, RestResultSalesStatus::class => \Paqtcom\Simplicate\Normalizer\RestResultSalesStatusNormalizer::class, RestResultHours::class => \Paqtcom\Simplicate\Normalizer\RestResultHoursNormalizer::class, RestResultHour::class => \Paqtcom\Simplicate\Normalizer\RestResultHourNormalizer::class, RestResultTimers::class => \Paqtcom\Simplicate\Normalizer\RestResultTimersNormalizer::class, RestResultTimer::class => \Paqtcom\Simplicate\Normalizer\RestResultTimerNormalizer::class, RestResultHourTypes::class => \Paqtcom\Simplicate\Normalizer\RestResultHourTypesNormalizer::class, RestResultHourType::class => \Paqtcom\Simplicate\Normalizer\RestResultHourTypeNormalizer::class, RestResultLeaveMultiple::class => \Paqtcom\Simplicate\Normalizer\RestResultLeaveMultipleNormalizer::class, RestResultLeave::class => \Paqtcom\Simplicate\Normalizer\RestResultLeaveNormalizer::class, RestResultLeaveBalances::class => \Paqtcom\Simplicate\Normalizer\RestResultLeaveBalancesNormalizer::class, RestResultLeaveTypes::class => \Paqtcom\Simplicate\Normalizer\RestResultLeaveTypesNormalizer::class, RestResultLeaveType::class => \Paqtcom\Simplicate\Normalizer\RestResultLeaveTypeNormalizer::class, RestResultTimelineMessage::class => \Paqtcom\Simplicate\Normalizer\RestResultTimelineMessageNormalizer::class, RestResultTimelineMessages::class => \Paqtcom\Simplicate\Normalizer\RestResultTimelineMessagesNormalizer::class, RestResultTimelineMessageType::class => \Paqtcom\Simplicate\Normalizer\RestResultTimelineMessageTypeNormalizer::class, RestResultTimelineMessageTypes::class => \Paqtcom\Simplicate\Normalizer\RestResultTimelineMessageTypesNormalizer::class, RestResultSalesProgressHistory::class => \Paqtcom\Simplicate\Normalizer\RestResultSalesProgressHistoryNormalizer::class, RestResultSalesProgressHistories::class => \Paqtcom\Simplicate\Normalizer\RestResultSalesProgressHistoriesNormalizer::class, RestResultDebtorList::class => \Paqtcom\Simplicate\Normalizer\RestResultDebtorListNormalizer::class, RestResultMileageList::class => \Paqtcom\Simplicate\Normalizer\RestResultMileageListNormalizer::class, RestResultMileage::class => \Paqtcom\Simplicate\Normalizer\RestResultMileageNormalizer::class, RestResultApprovalStatus::class => \Paqtcom\Simplicate\Normalizer\RestResultApprovalStatusNormalizer::class, RestResultApprovalStatusList::class => \Paqtcom\Simplicate\Normalizer\RestResultApprovalStatusListNormalizer::class, RestResultApproval::class => \Paqtcom\Simplicate\Normalizer\RestResultApprovalNormalizer::class, RestResultApprovals::class => \Paqtcom\Simplicate\Normalizer\RestResultApprovalsNormalizer::class, RestResultDocumentType::class => \Paqtcom\Simplicate\Normalizer\RestResultDocumentTypeNormalizer::class, RestResultDocumentTypes::class => \Paqtcom\Simplicate\Normalizer\RestResultDocumentTypesNormalizer::class, RestResultDocument::class => \Paqtcom\Simplicate\Normalizer\RestResultDocumentNormalizer::class, RestResultDocuments::class => \Paqtcom\Simplicate\Normalizer\RestResultDocumentsNormalizer::class, RestResultMergerCompare::class => \Paqtcom\Simplicate\Normalizer\RestResultMergerCompareNormalizer::class, RestResultMerger::class => \Paqtcom\Simplicate\Normalizer\RestResultMergerNormalizer::class, RestResultSalesReasons::class => \Paqtcom\Simplicate\Normalizer\RestResultSalesReasonsNormalizer::class, RestResultSalesReason::class => \Paqtcom\Simplicate\Normalizer\RestResultSalesReasonNormalizer::class, RestResultContactPersons::class => \Paqtcom\Simplicate\Normalizer\RestResultContactPersonsNormalizer::class, RestResultContactPerson::class => \Paqtcom\Simplicate\Normalizer\RestResultContactPersonNormalizer::class, RestResultSharedItems::class => \Paqtcom\Simplicate\Normalizer\RestResultSharedItemsNormalizer::class, RestResultSharedItem::class => \Paqtcom\Simplicate\Normalizer\RestResultSharedItemNormalizer::class, RestResultCustomFieldModels::class => \Paqtcom\Simplicate\Normalizer\RestResultCustomFieldModelsNormalizer::class, RestResultCustomFieldModel::class => \Paqtcom\Simplicate\Normalizer\RestResultCustomFieldModelNormalizer::class, RestResultCustomFieldTypes::class => \Paqtcom\Simplicate\Normalizer\RestResultCustomFieldTypesNormalizer::class, RestResultCustomFieldType::class => \Paqtcom\Simplicate\Normalizer\RestResultCustomFieldTypeNormalizer::class, RestResultCustomFieldOptions::class => \Paqtcom\Simplicate\Normalizer\RestResultCustomFieldOptionsNormalizer::class, RestResultCustomFieldOption::class => \Paqtcom\Simplicate\Normalizer\RestResultCustomFieldOptionNormalizer::class, RestResultCache::class => \Paqtcom\Simplicate\Normalizer\RestResultCacheNormalizer::class, RestResultPropositions::class => \Paqtcom\Simplicate\Normalizer\RestResultPropositionsNormalizer::class, RestResultProposition::class => \Paqtcom\Simplicate\Normalizer\RestResultPropositionNormalizer::class, RestResultReminderSets::class => \Paqtcom\Simplicate\Normalizer\RestResultReminderSetsNormalizer::class, RestResultReminderSet::class => \Paqtcom\Simplicate\Normalizer\RestResultReminderSetNormalizer::class, RestResultReminderTemplates::class => \Paqtcom\Simplicate\Normalizer\RestResultReminderTemplatesNormalizer::class, RestResultReminderTemplate::class => \Paqtcom\Simplicate\Normalizer\RestResultReminderTemplateNormalizer::class, RestResultPurchases::class => \Paqtcom\Simplicate\Normalizer\RestResultPurchasesNormalizer::class, RestResultPurchase::class => \Paqtcom\Simplicate\Normalizer\RestResultPurchaseNormalizer::class, RestResultReverseInvoices::class => \Paqtcom\Simplicate\Normalizer\RestResultReverseInvoicesNormalizer::class, RestResultReverseInvoice::class => \Paqtcom\Simplicate\Normalizer\RestResultReverseInvoiceNormalizer::class, RestResultQuoteTemplates::class => \Paqtcom\Simplicate\Normalizer\RestResultQuoteTemplatesNormalizer::class, RestResultQuoteTemplate::class => \Paqtcom\Simplicate\Normalizer\RestResultQuoteTemplateNormalizer::class, RestResultQuotes::class => \Paqtcom\Simplicate\Normalizer\RestResultQuotesNormalizer::class, RestResultQuote::class => \Paqtcom\Simplicate\Normalizer\RestResultQuoteNormalizer::class, RestResultQuoteStatuses::class => \Paqtcom\Simplicate\Normalizer\RestResultQuoteStatusesNormalizer::class, RestResultQuoteStatus::class => \Paqtcom\Simplicate\Normalizer\RestResultQuoteStatusNormalizer::class, RestResultProjectAssignments::class => \Paqtcom\Simplicate\Normalizer\RestResultProjectAssignmentsNormalizer::class, RestResultProjectAssignment::class => \Paqtcom\Simplicate\Normalizer\RestResultProjectAssignmentNormalizer::class, RestResultProjectAssignmentStatuses::class => \Paqtcom\Simplicate\Normalizer\RestResultProjectAssignmentStatusesNormalizer::class, RestResultProjectAssignmentStatus::class => \Paqtcom\Simplicate\Normalizer\RestResultProjectAssignmentStatusNormalizer::class, RestResultEmployeeExpenseList::class => \Paqtcom\Simplicate\Normalizer\RestResultEmployeeExpenseListNormalizer::class, RestResultEmployeeExpense::class => \Paqtcom\Simplicate\Normalizer\RestResultEmployeeExpenseNormalizer::class, RestResultProjectAssignmentbudget::class => \Paqtcom\Simplicate\Normalizer\RestResultProjectAssignmentbudgetNormalizer::class, RestResultAbsenceMultiple::class => \Paqtcom\Simplicate\Normalizer\RestResultAbsenceMultipleNormalizer::class, RestResultAbsence::class => \Paqtcom\Simplicate\Normalizer\RestResultAbsenceNormalizer::class, RestResultAbsenceTypes::class => \Paqtcom\Simplicate\Normalizer\RestResultAbsenceTypesNormalizer::class, RestResultAbsenceType::class => \Paqtcom\Simplicate\Normalizer\RestResultAbsenceTypeNormalizer::class, RestResultHoursSubmissions::class => \Paqtcom\Simplicate\Normalizer\RestResultHoursSubmissionsNormalizer::class, RestResultExternalItems::class => \Paqtcom\Simplicate\Normalizer\RestResultExternalItemsNormalizer::class, RestResultHoursTimesheetRow::class => \Paqtcom\Simplicate\Normalizer\RestResultHoursTimesheetRowNormalizer::class, RestResultHoursTimesheetRows::class => \Paqtcom\Simplicate\Normalizer\RestResultHoursTimesheetRowsNormalizer::class, RestResultDateTimeRange::class => \Paqtcom\Simplicate\Normalizer\RestResultDateTimeRangeNormalizer::class, GetReviewByWeek::class => \Paqtcom\Simplicate\Normalizer\GetReviewByWeekNormalizer::class, GetReviewByWeekDetails::class => \Paqtcom\Simplicate\Normalizer\GetReviewByWeekDetailsNormalizer::class, GetReviewByWeekId::class => \Paqtcom\Simplicate\Normalizer\GetReviewByWeekIdNormalizer::class, ReviewByWeekMetaData::class => \Paqtcom\Simplicate\Normalizer\ReviewByWeekMetaDataNormalizer::class, Right::class => \Paqtcom\Simplicate\Normalizer\RightNormalizer::class, GetQuote::class => \Paqtcom\Simplicate\Normalizer\GetQuoteNormalizer::class, GetSales::class => \Paqtcom\Simplicate\Normalizer\GetSalesNormalizer::class, GetSalesService::class => \Paqtcom\Simplicate\Normalizer\GetSalesServiceNormalizer::class, GetSeparateInvoiceRecipient::class => \Paqtcom\Simplicate\Normalizer\GetSeparateInvoiceRecipientNormalizer::class, LostToCompetitor::class => \Paqtcom\Simplicate\Normalizer\LostToCompetitorNormalizer::class, PostDuplicateSales::class => \Paqtcom\Simplicate\Normalizer\PostDuplicateSalesNormalizer::class, PostQuote::class => \Paqtcom\Simplicate\Normalizer\PostQuoteNormalizer::class, PostSales::class => \Paqtcom\Simplicate\Normalizer\PostSalesNormalizer::class, PostSalesService::class => \Paqtcom\Simplicate\Normalizer\PostSalesServiceNormalizer::class, PostSeparateInvoiceRecipient::class => \Paqtcom\Simplicate\Normalizer\PostSeparateInvoiceRecipientNormalizer::class, PutQuoteEmail::class => \Paqtcom\Simplicate\Normalizer\PutQuoteEmailNormalizer::class, Quote::class => \Paqtcom\Simplicate\Normalizer\QuoteNormalizer::class, QuoteContentBlock::class => \Paqtcom\Simplicate\Normalizer\QuoteContentBlockNormalizer::class, QuotePortalLabel::class => \Paqtcom\Simplicate\Normalizer\QuotePortalLabelNormalizer::class, QuoteSalesService::class => \Paqtcom\Simplicate\Normalizer\QuoteSalesServiceNormalizer::class, QuoteStatus::class => \Paqtcom\Simplicate\Normalizer\QuoteStatusNormalizer::class, QuotetemplateConfigurationMetaData::class => \Paqtcom\Simplicate\Normalizer\QuotetemplateConfigurationMetaDataNormalizer::class, QuotetemplateMetaData::class => \Paqtcom\Simplicate\Normalizer\QuotetemplateMetaDataNormalizer::class, RecentSalesQuote::class => \Paqtcom\Simplicate\Normalizer\RecentSalesQuoteNormalizer::class, RecentSalesQuoteStatus::class => \Paqtcom\Simplicate\Normalizer\RecentSalesQuoteStatusNormalizer::class, RevenueGroup::class => \Paqtcom\Simplicate\Normalizer\RevenueGroupNormalizer::class, Sales::class => \Paqtcom\Simplicate\Normalizer\SalesNormalizer::class, SalesProgress::class => \Paqtcom\Simplicate\Normalizer\SalesProgressNormalizer::class, SalesProgressHistory::class => \Paqtcom\Simplicate\Normalizer\SalesProgressHistoryNormalizer::class, SalesReason::class => \Paqtcom\Simplicate\Normalizer\SalesReasonNormalizer::class, SalesService::class => \Paqtcom\Simplicate\Normalizer\SalesServiceNormalizer::class, SalesSource::class => \Paqtcom\Simplicate\Normalizer\SalesSourceNormalizer::class, SalesStatus::class => \Paqtcom\Simplicate\Normalizer\SalesStatusNormalizer::class, SeparateInvoiceRecipient::class => \Paqtcom\Simplicate\Normalizer\SeparateInvoiceRecipientNormalizer::class, DefaultService::class => \Paqtcom\Simplicate\Normalizer\DefaultServiceNormalizer::class, GetDefaultService::class => \Paqtcom\Simplicate\Normalizer\GetDefaultServiceNormalizer::class, GetService::class => \Paqtcom\Simplicate\Normalizer\GetServiceNormalizer::class, Installment::class => \Paqtcom\Simplicate\Normalizer\InstallmentNormalizer::class, PostDefaultService::class => \Paqtcom\Simplicate\Normalizer\PostDefaultServiceNormalizer::class, PostService::class => \Paqtcom\Simplicate\Normalizer\PostServiceNormalizer::class, Service::class => \Paqtcom\Simplicate\Normalizer\ServiceNormalizer::class, GetSharedItem::class => \Paqtcom\Simplicate\Normalizer\GetSharedItemNormalizer::class, IsSatisfied::class => \Paqtcom\Simplicate\Normalizer\IsSatisfiedNormalizer::class, IsSatisfiedReason::class => \Paqtcom\Simplicate\Normalizer\IsSatisfiedReasonNormalizer::class, PostSharedItem::class => \Paqtcom\Simplicate\Normalizer\PostSharedItemNormalizer::class, Task::class => \Paqtcom\Simplicate\Normalizer\TaskNormalizer::class, Attachment::class => \Paqtcom\Simplicate\Normalizer\AttachmentNormalizer::class, AttachmentType::class => \Paqtcom\Simplicate\Normalizer\AttachmentTypeNormalizer::class, ContentField::class => \Paqtcom\Simplicate\Normalizer\ContentFieldNormalizer::class, Creator::class => \Paqtcom\Simplicate\Normalizer\CreatorNormalizer::class, GetMessage::class => \Paqtcom\Simplicate\Normalizer\GetMessageNormalizer::class, LinkedToEntity::class => \Paqtcom\Simplicate\Normalizer\LinkedToEntityNormalizer::class, Message::class => \Paqtcom\Simplicate\Normalizer\MessageNormalizer::class, MessageType::class => \Paqtcom\Simplicate\Normalizer\MessageTypeNormalizer::class, PostAttachment::class => \Paqtcom\Simplicate\Normalizer\PostAttachmentNormalizer::class, PostMessage::class => \Paqtcom\Simplicate\Normalizer\PostMessageNormalizer::class, PostMessageLinkedTo::class => \Paqtcom\Simplicate\Normalizer\PostMessageLinkedToNormalizer::class, GetTimer::class => \Paqtcom\Simplicate\Normalizer\GetTimerNormalizer::class, PostTimer::class => \Paqtcom\Simplicate\Normalizer\PostTimerNormalizer::class, PutTimer::class => \Paqtcom\Simplicate\Normalizer\PutTimerNormalizer::class, Timer::class => \Paqtcom\Simplicate\Normalizer\TimerNormalizer::class, PostChunked::class => \Paqtcom\Simplicate\Normalizer\PostChunkedNormalizer::class, PutChunked::class => \Paqtcom\Simplicate\Normalizer\PutChunkedNormalizer::class, Avatar::class => \Paqtcom\Simplicate\Normalizer\AvatarNormalizer::class, AvatarPublic::class => \Paqtcom\Simplicate\Normalizer\AvatarPublicNormalizer::class, AvatarSimple::class => \Paqtcom\Simplicate\Normalizer\AvatarSimpleNormalizer::class, User::class => \Paqtcom\Simplicate\Normalizer\UserNormalizer::class, Comment::class => \Paqtcom\Simplicate\Normalizer\CommentNormalizer::class, CreatedBy::class => \Paqtcom\Simplicate\Normalizer\CreatedByNormalizer::class, CurrentTask::class => \Paqtcom\Simplicate\Normalizer\CurrentTaskNormalizer::class, CurrentTaskEmployee::class => \Paqtcom\Simplicate\Normalizer\CurrentTaskEmployeeNormalizer::class, DefaultAction::class => \Paqtcom\Simplicate\Normalizer\DefaultActionNormalizer::class, DefaultTask::class => \Paqtcom\Simplicate\Normalizer\DefaultTaskNormalizer::class, DefaultWorkflow::class => \Paqtcom\Simplicate\Normalizer\DefaultWorkflowNormalizer::class, DefaultWorkflowGroup::class => \Paqtcom\Simplicate\Normalizer\DefaultWorkflowGroupNormalizer::class, GetDefaultAction::class => \Paqtcom\Simplicate\Normalizer\GetDefaultActionNormalizer::class, GetDefaultTask::class => \Paqtcom\Simplicate\Normalizer\GetDefaultTaskNormalizer::class, GetDefaultWorkflow::class => \Paqtcom\Simplicate\Normalizer\GetDefaultWorkflowNormalizer::class, GetDefaultWorkflowGroup::class => \Paqtcom\Simplicate\Normalizer\GetDefaultWorkflowGroupNormalizer::class, GetSimpleDefaultTask::class => \Paqtcom\Simplicate\Normalizer\GetSimpleDefaultTaskNormalizer::class, GetSimpleDefaultWorkflow::class => \Paqtcom\Simplicate\Normalizer\GetSimpleDefaultWorkflowNormalizer::class, GetWorkflow::class => \Paqtcom\Simplicate\Normalizer\GetWorkflowNormalizer::class, LinkedTo::class => \Paqtcom\Simplicate\Normalizer\LinkedToNormalizer::class, PostWorkflow::class => \Paqtcom\Simplicate\Normalizer\PostWorkflowNormalizer::class, Workflow::class => \Paqtcom\Simplicate\Normalizer\WorkflowNormalizer::class, WorkflowItem::class => \Paqtcom\Simplicate\Normalizer\WorkflowItemNormalizer::class, WorkflowItemType::class => \Paqtcom\Simplicate\Normalizer\WorkflowItemTypeNormalizer::class, '\\' . Reference::class => '\\' . ReferenceNormalizer::class];
    protected array $normalizersCache = [];

    public function supportsDenormalization($data, $type, $format = null, array $context = []): bool
    {
        return array_key_exists($type, $this->normalizers);
    }

    public function supportsNormalization($data, $format = null, array $context = []): bool
    {
        return is_object($data) && array_key_exists($data::class, $this->normalizers);
    }

    public function normalize($object, $format = null, array $context = []): float|int|bool|ArrayObject|array|string|null
    {
        $normalizerClass = $this->normalizers[$object::class];
        $normalizer = $this->getNormalizer($normalizerClass);

        return $normalizer->normalize($object, $format, $context);
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        $denormalizerClass = $this->normalizers[$class];
        $denormalizer = $this->getNormalizer($denormalizerClass);

        return $denormalizer->denormalize($data, $class, $format, $context);
    }

    private function getNormalizer(string $normalizerClass)
    {
        return $this->normalizersCache[$normalizerClass] ?? $this->initNormalizer($normalizerClass);
    }

    private function initNormalizer(string $normalizerClass)
    {
        $normalizer = new $normalizerClass();
        $normalizer->setNormalizer($this->normalizer);
        $normalizer->setDenormalizer($this->denormalizer);
        $this->normalizersCache[$normalizerClass] = $normalizer;

        return $normalizer;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [
            Feature::class => false, Setting::class => false, App::class => false, Log::class => false, ServiceGroup::class => false, BaseSetting::class => false, Expense::class => false, ExpenseAttachment::class => false, PostExpense::class => false, Accountancy::class => false, Address::class => false, Administration::class => false, ContactPerson::class => false, Country::class => false, CustomerGroup::class => false, Debtor::class => false, DebtorList::class => false, ExternalList::class => false, ExternalListTag::class => false, Gender::class => false, GetAddress::class => false, GetBasicPersonSimple::class => false, GetContactPerson::class => false, GetContactSimple::class => false, GetDebtor::class => false, GetInterest::class => false, GetMyOrganizationProfileSimple::class => false, GetOrganization::class => false, GetOrganizationDebtorSimple::class => false, GetOrganizationSimple::class => false, GetPerson::class => false, GetPersonDebtorSimple::class => false, GetPersonSimple::class => false, Industry::class => false, Interest::class => false, MailingList::class => false, MyOrganizationProfile::class => false, Organization::class => false, OrganizationContact::class => false, OrganizationSize::class => false, Person::class => false, PersonContact::class => false, PersonMailingList::class => false, PostAddress::class => false, PostContactOrganizationFk::class => false, PostContactPerson::class => false, PostContactPersonFk::class => false, PostContactPersonProperties::class => false, PostDebtor::class => false, PostInterest::class => false, PostOrganization::class => false, PostOrganizationFk::class => false, PostPerson::class => false, PostTeam::class => false, PutContactPerson::class => false, RelationType::class => false, SbiCode::class => false, Timezone::class => false, CustomField::class => false, CustomFieldGroup::class => false, CustomFieldModel::class => false, CustomFieldOption::class => false, CustomFieldType::class => false, GetCustomField::class => false, PostCustomFieldValue::class => false, Document::class => false, DocumentType::class => false, DocumentTypeSimple::class => false, GetDocument::class => false, GetDocumentType::class => false, PostDocument::class => false, PostDocumentLinkedTo::class => false, PostQuoteTemplate::class => false, PutDocument::class => false, QuoteTemplate::class => false, Filter::class => false, Approval::class => false, ApprovalStatus::class => false, BaseHours::class => false, CalendarItem::class => false, Correction::class => false, DateTimeRange::class => false, ExternalItemMetadata::class => false, ExternalItemMetadataConfiguration::class => false, GetApproval::class => false, GetApprovalStatus::class => false, GetHours::class => false, GetHoursHoursProjectService::class => false, GetHoursProjectService::class => false, GetHoursSimple::class => false, GetHoursType::class => false, GetLeaveType::class => false, GetProjectServiceCostType::class => false, GetProjectServiceHoursType::class => false, GetSalesServiceCostType::class => false, GetSalesServiceHoursType::class => false, GetServiceCostType::class => false, Hours::class => false, HoursType::class => false, LeaveStatus::class => false, MileageType::class => false, PostApproval::class => false, PostCalendarItem::class => false, PostHours::class => false, PostHoursType::class => false, PostProjectServiceHoursType::class => false, PostSubmission::class => false, PostTimesheetRow::class => false, ProjectServiceCostType::class => false, ProjectServiceHoursType::class => false, Recurrence::class => false, Rrule::class => false, SalesServiceCostType::class => false, SalesServiceHoursType::class => false, ServiceCostType::class => false, SubmissionStatus::class => false, Submit::class => false, GetTimesheetRow::class => false, GetTimesheetRowItemtype::class => false, GetTimesheetRowOrganizationRelation::class => false, GetTimesheetRowPersonRelation::class => false, GetTimesheetRowProject::class => false, GetTimesheetRowProjectService::class => false, TimesheetRow::class => false, Absence::class => false, AbsenceType::class => false, CivilStatus::class => false, Contract::class => false, ContractType::class => false, Employee::class => false, EmployeeStatus::class => false, EmployeeType::class => false, EmploymentType::class => false, GetAbsence::class => false, GetAbsenceType::class => false, GetCivilStatus::class => false, GetContract::class => false, GetEmployee::class => false, GetEmployeeSimple::class => false, GetLeave::class => false, HrmGetLeaveType::class => false, GetTeam::class => false, GetTeamSimple::class => false, GetTimetable::class => false, Leave::class => false, LeaveBalance::class => false, LeaveType::class => false, PostAbsence::class => false, PostEmployee::class => false, PostEmployeeFk::class => false, PostEmployeeStatusFk::class => false, PostLeave::class => false, HrmPostTeam::class => false, PostTimetable::class => false, PutEmployee::class => false, PutTimetable::class => false, Team::class => false, Timetable::class => false, TimetableWeek::class => false, TimetableWeekDay::class => false, EmailAttachment::class => false, EmailMessage::class => false, Inbox::class => false, GetInvoice::class => false, GetInvoiceLine::class => false, GetInvoiceReminder::class => false, GetInvoiceSimple::class => false, GetPayment::class => false, GetPaymentTerm::class => false, GetProposition::class => false, GetReminderSet::class => false, GetReminderSetSimple::class => false, Invoice::class => false, InvoiceLine::class => false, InvoiceStatus::class => false, InvoiceTemplate::class => false, Journal::class => false, JournalLine::class => false, JournalVat::class => false, Payment::class => false, PaymentTerm::class => false, PostInvoice::class => false, PostInvoiceLine::class => false, PostVatClassFk::class => false, ReminderSet::class => false, ReminderSetTemplate::class => false, ReminderTemplate::class => false, SubscriptionCycle::class => false, VatClass::class => false, PostMerger::class => false, PostMergerCompare::class => false, ResultMergerMerge::class => false, ResultPostMergerCompare::class => false, MetaData::class => false, GetMileage::class => false, GetMileageSimple::class => false, Mileage::class => false, PostMileage::class => false, PutMileage::class => false, PkRestResult::class => false, Assignment::class => false, AssignmentBudget::class => false, AssignmentBudgetInfo::class => false, AssignmentBudgetInfoFuturePast::class => false, AssignmentBudgetInfoMetaData::class => false, AssignmentStatus::class => false, Budget::class => false, BudgetCosts::class => false, BudgetHours::class => false, BudgetTotal::class => false, GetAssignment::class => false, GetAssignmentSimple::class => false, GetAssignmentStatus::class => false, GetProject::class => false, GetProjectService::class => false, GetProjectServiceSimple::class => false, GetProjectSimple::class => false, GetPurchaseType::class => false, PostAssignment::class => false, PostProject::class => false, PostProjectService::class => false, PostPurchaseType::class => false, Project::class => false, ProjectAssignmentDeleteResultRest::class => false, ProjectEmployee::class => false, ProjectManager::class => false, ProjectStatus::class => false, Purchase::class => false, PurchaseType::class => false, PutAssignment::class => false, PutProjectService::class => false, ReverseInvoice::class => false, AppReceiverSetting::class => false, AppReceivers::class => false, RestBatchValidationError::class => false, RestError::class => false, RestResultApps::class => false, RestResultApp::class => false, RestResultLogs::class => false, RestResultLog::class => false, RestResultCustomFieldGroups::class => false, RestResultCustomFieldGroup::class => false, RestResultCustomFields::class => false, RestResultCustomField::class => false, RestResultServiceGroups::class => false, RestResultServiceGroup::class => false, RestResultSettings::class => false, RestResultSetting::class => false, RestResultAdministrations::class => false, RestResultAdministration::class => false, RestResultMyOrganizationProfiles::class => false, RestResultMyOrganizationProfile::class => false, RestResultContacts::class => false, RestResultContact::class => false, RestResultOrganizations::class => false, RestResultOrganization::class => false, RestResultPersons::class => false, RestResultPerson::class => false, RestResultRelationTypes::class => false, RestResultRelationType::class => false, RestResultCountries::class => false, RestResultCountry::class => false, RestResultGenders::class => false, RestResultGender::class => false, RestResultTimetables::class => false, RestResultTimetable::class => false, RestResultContractTypes::class => false, RestResultContractType::class => false, RestResultEmploymentTypes::class => false, RestResultEmploymentType::class => false, RestResultEmployeeTypes::class => false, RestResultEmployeeType::class => false, RestResultCivilStatuses::class => false, RestResultCivilStatus::class => false, RestResultOrganizationSizes::class => false, RestResultOrganizationSize::class => false, RestResultContracts::class => false, RestResultContract::class => false, RestResultTeams::class => false, RestResultTeam::class => false, RestResultIndustries::class => false, RestResultIndustry::class => false, RestResultInterests::class => false, RestResultInterest::class => false, RestResultEmployees::class => false, RestResultEmployee::class => false, RestResultInvoices::class => false, RestResultInvoice::class => false, RestResultInvoiceStatuses::class => false, RestResultInvoiceStatus::class => false, RestResultJournals::class => false, RestResultJournal::class => false, RestResultPayments::class => false, RestResultPayment::class => false, RestResultPaymentTerms::class => false, RestResultPaymentTerm::class => false, RestResultVatClasses::class => false, RestResultVatClass::class => false, RestResultProjects::class => false, RestResultProject::class => false, RestResultProjectEmployees::class => false, RestResultProjectEmployee::class => false, RestResultProjectStatusses::class => false, RestResultProjectStatus::class => false, RestResultProjectServices::class => false, RestResultProjectService::class => false, RestResultPurchaseTypes::class => false, RestResultPurchaseType::class => false, RestResultServices::class => false, RestResultService::class => false, RestResultSalesServices::class => false, RestResultSalesService::class => false, RestResultDefaultServices::class => false, RestResultDefaultService::class => false, RestResultWorkflows::class => false, RestResultWorkflow::class => false, RestResultWorkflowItems::class => false, RestResultWorkflowItem::class => false, RestResultWorkflowItemTypes::class => false, RestResultWorkflowItemType::class => false, RestResultTasks::class => false, RestResultTask::class => false, RestResultSales::class => false, RestResultSale::class => false, RestResultRevenueGroups::class => false, RestResultRevenueGroup::class => false, RestResultSalesProgresses::class => false, RestResultSalesProgress::class => false, RestResultSalesSources::class => false, RestResultSalesSource::class => false, RestResultSalesStatusses::class => false, RestResultSalesStatus::class => false, RestResultHours::class => false, RestResultHour::class => false, RestResultTimers::class => false, RestResultTimer::class => false, RestResultHourTypes::class => false, RestResultHourType::class => false, RestResultLeaveMultiple::class => false, RestResultLeave::class => false, RestResultLeaveBalances::class => false, RestResultLeaveTypes::class => false, RestResultLeaveType::class => false, RestResultTimelineMessage::class => false, RestResultTimelineMessages::class => false, RestResultTimelineMessageType::class => false, RestResultTimelineMessageTypes::class => false, RestResultSalesProgressHistory::class => false, RestResultSalesProgressHistories::class => false, RestResultDebtorList::class => false, RestResultMileageList::class => false, RestResultMileage::class => false, RestResultApprovalStatus::class => false, RestResultApprovalStatusList::class => false, RestResultApproval::class => false, RestResultApprovals::class => false, RestResultDocumentType::class => false, RestResultDocumentTypes::class => false, RestResultDocument::class => false, RestResultDocuments::class => false, RestResultMergerCompare::class => false, RestResultMerger::class => false, RestResultSalesReasons::class => false, RestResultSalesReason::class => false, RestResultContactPersons::class => false, RestResultContactPerson::class => false, RestResultSharedItems::class => false, RestResultSharedItem::class => false, RestResultCustomFieldModels::class => false, RestResultCustomFieldModel::class => false, RestResultCustomFieldTypes::class => false, RestResultCustomFieldType::class => false, RestResultCustomFieldOptions::class => false, RestResultCustomFieldOption::class => false, RestResultCache::class => false, RestResultPropositions::class => false, RestResultProposition::class => false, RestResultReminderSets::class => false, RestResultReminderSet::class => false, RestResultReminderTemplates::class => false, RestResultReminderTemplate::class => false, RestResultPurchases::class => false, RestResultPurchase::class => false, RestResultReverseInvoices::class => false, RestResultReverseInvoice::class => false, RestResultQuoteTemplates::class => false, RestResultQuoteTemplate::class => false, RestResultQuotes::class => false, RestResultQuote::class => false, RestResultQuoteStatuses::class => false, RestResultQuoteStatus::class => false, RestResultProjectAssignments::class => false, RestResultProjectAssignment::class => false, RestResultProjectAssignmentStatuses::class => false, RestResultProjectAssignmentStatus::class => false, RestResultEmployeeExpenseList::class => false, RestResultEmployeeExpense::class => false, RestResultProjectAssignmentbudget::class => false, RestResultAbsenceMultiple::class => false, RestResultAbsence::class => false, RestResultAbsenceTypes::class => false, RestResultAbsenceType::class => false, RestResultHoursSubmissions::class => false, RestResultExternalItems::class => false, RestResultHoursTimesheetRow::class => false, RestResultHoursTimesheetRows::class => false, RestResultDateTimeRange::class => false, GetReviewByWeek::class => false, GetReviewByWeekDetails::class => false, GetReviewByWeekId::class => false, ReviewByWeekMetaData::class => false, Right::class => false, GetQuote::class => false, GetSales::class => false, GetSalesService::class => false, GetSeparateInvoiceRecipient::class => false, LostToCompetitor::class => false, PostDuplicateSales::class => false, PostQuote::class => false, PostSales::class => false, PostSalesService::class => false, PostSeparateInvoiceRecipient::class => false, PutQuoteEmail::class => false, Quote::class => false, QuoteContentBlock::class => false, QuotePortalLabel::class => false, QuoteSalesService::class => false, QuoteStatus::class => false, QuotetemplateConfigurationMetaData::class => false, QuotetemplateMetaData::class => false, RecentSalesQuote::class => false, RecentSalesQuoteStatus::class => false, RevenueGroup::class => false, Sales::class => false, SalesProgress::class => false, SalesProgressHistory::class => false, SalesReason::class => false, SalesService::class => false, SalesSource::class => false, SalesStatus::class => false, SeparateInvoiceRecipient::class => false, DefaultService::class => false, GetDefaultService::class => false, GetService::class => false, Installment::class => false, PostDefaultService::class => false, PostService::class => false, Service::class => false, GetSharedItem::class => false, IsSatisfied::class => false, IsSatisfiedReason::class => false, PostSharedItem::class => false, Task::class => false, Attachment::class => false, AttachmentType::class => false, ContentField::class => false, Creator::class => false, GetMessage::class => false, LinkedToEntity::class => false, Message::class => false, MessageType::class => false, PostAttachment::class => false, PostMessage::class => false, PostMessageLinkedTo::class => false, GetTimer::class => false, PostTimer::class => false, PutTimer::class => false, Timer::class => false, PostChunked::class => false, PutChunked::class => false, Avatar::class => false, AvatarPublic::class => false, AvatarSimple::class => false, User::class => false, Comment::class => false, CreatedBy::class => false, CurrentTask::class => false, CurrentTaskEmployee::class => false, DefaultAction::class => false, DefaultTask::class => false, DefaultWorkflow::class => false, DefaultWorkflowGroup::class => false, GetDefaultAction::class => false, GetDefaultTask::class => false, GetDefaultWorkflow::class => false, GetDefaultWorkflowGroup::class => false, GetSimpleDefaultTask::class => false, GetSimpleDefaultWorkflow::class => false, GetWorkflow::class => false, LinkedTo::class => false, PostWorkflow::class => false, Workflow::class => false, WorkflowItem::class => false, WorkflowItemType::class => false, '\\' . Reference::class => false];
    }
}
