<?php
/**
 * GetDocumentTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Simplicate API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@simplicate.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetDocumentTypeTest Class Doc Comment
 *
 * @category    Class
 * @description GetDocumentType
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetDocumentTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetDocumentType"
     */
    public function testGetDocumentType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "can_have_attachment"
     */
    public function testPropertyCanHaveAttachment()
    {
    }

    /**
     * Test attribute "is_for_crm"
     */
    public function testPropertyIsForCrm()
    {
    }

    /**
     * Test attribute "is_for_contact"
     */
    public function testPropertyIsForContact()
    {
    }

    /**
     * Test attribute "is_for_sale"
     */
    public function testPropertyIsForSale()
    {
    }

    /**
     * Test attribute "is_for_debtor"
     */
    public function testPropertyIsForDebtor()
    {
    }

    /**
     * Test attribute "is_for_project"
     */
    public function testPropertyIsForProject()
    {
    }

    /**
     * Test attribute "is_for_subscription"
     */
    public function testPropertyIsForSubscription()
    {
    }

    /**
     * Test attribute "is_for_employee"
     */
    public function testPropertyIsForEmployee()
    {
    }

    /**
     * Test attribute "is_for_invoice"
     */
    public function testPropertyIsForInvoice()
    {
    }

    /**
     * Test attribute "is_for_myorganizationprofile"
     */
    public function testPropertyIsForMyorganizationprofile()
    {
    }

    /**
     * Test attribute "is_blocked"
     */
    public function testPropertyIsBlocked()
    {
    }

    /**
     * Test attribute "is_visible_on_all"
     */
    public function testPropertyIsVisibleOnAll()
    {
    }
}
