<?php
/**
 * GetHoursTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Simplicate API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@simplicate.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetHoursTest Class Doc Comment
 *
 * @category    Class
 * @description GetHours
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetHoursTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetHours"
     */
    public function testGetHours()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "employee"
     */
    public function testPropertyEmployee()
    {
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
    }

    /**
     * Test attribute "projectservice"
     */
    public function testPropertyProjectservice()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "approvalstatus"
     */
    public function testPropertyApprovalstatus()
    {
    }

    /**
     * Test attribute "invoice_status"
     */
    public function testPropertyInvoiceStatus()
    {
    }

    /**
     * Test attribute "invoice_id"
     */
    public function testPropertyInvoiceId()
    {
    }

    /**
     * Test attribute "invoiceline_id"
     */
    public function testPropertyInvoicelineId()
    {
    }

    /**
     * Test attribute "tariff"
     */
    public function testPropertyTariff()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "locked"
     */
    public function testPropertyLocked()
    {
    }

    /**
     * Test attribute "is_editable"
     */
    public function testPropertyIsEditable()
    {
    }

    /**
     * Test attribute "is_deletable"
     */
    public function testPropertyIsDeletable()
    {
    }

    /**
     * Test attribute "leave_status"
     */
    public function testPropertyLeaveStatus()
    {
    }

    /**
     * Test attribute "leave_id"
     */
    public function testPropertyLeaveId()
    {
    }

    /**
     * Test attribute "absence_id"
     */
    public function testPropertyAbsenceId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "corrections"
     */
    public function testPropertyCorrections()
    {
    }

    /**
     * Test attribute "mileage"
     */
    public function testPropertyMileage()
    {
    }

    /**
     * Test attribute "is_productive"
     */
    public function testPropertyIsProductive()
    {
    }

    /**
     * Test attribute "hours"
     */
    public function testPropertyHours()
    {
    }

    /**
     * Test attribute "duration_in_minutes"
     */
    public function testPropertyDurationInMinutes()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "is_time_defined"
     */
    public function testPropertyIsTimeDefined()
    {
    }

    /**
     * Test attribute "is_recurring"
     */
    public function testPropertyIsRecurring()
    {
    }

    /**
     * Test attribute "recurrence"
     */
    public function testPropertyRecurrence()
    {
    }

    /**
     * Test attribute "is_external"
     */
    public function testPropertyIsExternal()
    {
    }

    /**
     * Test attribute "billable"
     */
    public function testPropertyBillable()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "assignment_id"
     */
    public function testPropertyAssignmentId()
    {
    }

    /**
     * Test attribute "should_sync_to_cronofy"
     */
    public function testPropertyShouldSyncToCronofy()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }
}
