<?php
/**
 * GetReviewByWeekDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Simplicate API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@simplicate.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetReviewByWeekDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description GetReviewByWeekDetails
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetReviewByWeekDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetReviewByWeekDetails"
     */
    public function testGetReviewByWeekDetails()
    {
    }

    /**
     * Test attribute "employee"
     */
    public function testPropertyEmployee()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "status_id"
     */
    public function testPropertyStatusId()
    {
    }

    /**
     * Test attribute "status_category"
     */
    public function testPropertyStatusCategory()
    {
    }

    /**
     * Test attribute "status_label"
     */
    public function testPropertyStatusLabel()
    {
    }

    /**
     * Test attribute "raster_hours"
     */
    public function testPropertyRasterHours()
    {
    }

    /**
     * Test attribute "written_hours"
     */
    public function testPropertyWrittenHours()
    {
    }

    /**
     * Test attribute "overtime"
     */
    public function testPropertyOvertime()
    {
    }

    /**
     * Test attribute "leave"
     */
    public function testPropertyLeave()
    {
    }

    /**
     * Test attribute "absence"
     */
    public function testPropertyAbsence()
    {
    }

    /**
     * Test attribute "mileage"
     */
    public function testPropertyMileage()
    {
    }

    /**
     * Test attribute "costs"
     */
    public function testPropertyCosts()
    {
    }

    /**
     * Test attribute "declarability"
     */
    public function testPropertyDeclarability()
    {
    }

    /**
     * Test attribute "productivity"
     */
    public function testPropertyProductivity()
    {
    }

    /**
     * Test attribute "productivity_target"
     */
    public function testPropertyProductivityTarget()
    {
    }

    /**
     * Test attribute "productivity_value"
     */
    public function testPropertyProductivityValue()
    {
    }

    /**
     * Test attribute "productivity_value_target"
     */
    public function testPropertyProductivityValueTarget()
    {
    }
}
