<?php
/**
 * PostDebtorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Simplicate API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@simplicate.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PostDebtorTest Class Doc Comment
 *
 * @category    Class
 * @description PostDebtor
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostDebtorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PostDebtor"
     */
    public function testPostDebtor()
    {
    }

    /**
     * Test attribute "payment_term_id"
     */
    public function testPropertyPaymentTermId()
    {
    }

    /**
     * Test attribute "provision_method"
     */
    public function testPropertyProvisionMethod()
    {
    }

    /**
     * Test attribute "send_invoice_email_to_contact"
     */
    public function testPropertySendInvoiceEmailToContact()
    {
    }

    /**
     * Test attribute "provision_contactperson_id"
     */
    public function testPropertyProvisionContactpersonId()
    {
    }

    /**
     * Test attribute "send_invoice_email_to_project_contact"
     */
    public function testPropertySendInvoiceEmailToProjectContact()
    {
    }

    /**
     * Test attribute "send_invoice_email_to_fixed_email"
     */
    public function testPropertySendInvoiceEmailToFixedEmail()
    {
    }

    /**
     * Test attribute "send_email_email"
     */
    public function testPropertySendEmailEmail()
    {
    }

    /**
     * Test attribute "send_invoice_email_to_cc"
     */
    public function testPropertySendInvoiceEmailToCc()
    {
    }

    /**
     * Test attribute "cc"
     */
    public function testPropertyCc()
    {
    }

    /**
     * Test attribute "attention_to"
     */
    public function testPropertyAttentionTo()
    {
    }

    /**
     * Test attribute "attention_to_person_id"
     */
    public function testPropertyAttentionToPersonId()
    {
    }

    /**
     * Test attribute "attention_to_fixed"
     */
    public function testPropertyAttentionToFixed()
    {
    }

    /**
     * Test attribute "autocollect"
     */
    public function testPropertyAutocollect()
    {
    }

    /**
     * Test attribute "reminders"
     */
    public function testPropertyReminders()
    {
    }

    /**
     * Test attribute "send_email_type"
     */
    public function testPropertySendEmailType()
    {
    }

    /**
     * Test attribute "autosend_subscription_invoice"
     */
    public function testPropertyAutosendSubscriptionInvoice()
    {
    }

    /**
     * Test attribute "invoicetemplate_id"
     */
    public function testPropertyInvoicetemplateId()
    {
    }
}
