<?php
/**
 * QuoteSalesServiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Simplicate API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@simplicate.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QuoteSalesServiceTest Class Doc Comment
 *
 * @category    Class
 * @description QuoteSalesService
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuoteSalesServiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QuoteSalesService"
     */
    public function testQuoteSalesService()
    {
    }

    /**
     * Test attribute "vat_code"
     */
    public function testPropertyVatCode()
    {
    }

    /**
     * Test attribute "vat_description"
     */
    public function testPropertyVatDescription()
    {
    }

    /**
     * Test attribute "sales_id"
     */
    public function testPropertySalesId()
    {
    }

    /**
     * Test attribute "default_service_id"
     */
    public function testPropertyDefaultServiceId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "invoice_method"
     */
    public function testPropertyInvoiceMethod()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "show_itemtype"
     */
    public function testPropertyShowItemtype()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "position"
     */
    public function testPropertyPosition()
    {
    }

    /**
     * Test attribute "subscription_cycle"
     */
    public function testPropertySubscriptionCycle()
    {
    }

    /**
     * Test attribute "explanation"
     */
    public function testPropertyExplanation()
    {
    }

    /**
     * Test attribute "track_hours"
     */
    public function testPropertyTrackHours()
    {
    }

    /**
     * Test attribute "track_cost"
     */
    public function testPropertyTrackCost()
    {
    }
}
