<?php
/**
 * QuotetemplateConfigurationMetaDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Simplicate API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: support@simplicate.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QuotetemplateConfigurationMetaDataTest Class Doc Comment
 *
 * @category    Class
 * @description QuotetemplateConfigurationMetaData
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuotetemplateConfigurationMetaDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QuotetemplateConfigurationMetaData"
     */
    public function testQuotetemplateConfigurationMetaData()
    {
    }

    /**
     * Test attribute "default_view_and_sign_button_text"
     */
    public function testPropertyDefaultViewAndSignButtonText()
    {
    }

    /**
     * Test attribute "default_view_and_sign_button_bg_color"
     */
    public function testPropertyDefaultViewAndSignButtonBgColor()
    {
    }

    /**
     * Test attribute "default_view_and_sign_button_text_color"
     */
    public function testPropertyDefaultViewAndSignButtonTextColor()
    {
    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
    }

    /**
     * Test attribute "total_count"
     */
    public function testPropertyTotalCount()
    {
    }

    /**
     * Test attribute "offset"
     */
    public function testPropertyOffset()
    {
    }

    /**
     * Test attribute "limit"
     */
    public function testPropertyLimit()
    {
    }

    /**
     * Test attribute "upper_limit"
     */
    public function testPropertyUpperLimit()
    {
    }

    /**
     * Test attribute "nocleanup"
     */
    public function testPropertyNocleanup()
    {
    }

    /**
     * Test attribute "checksum"
     */
    public function testPropertyChecksum()
    {
    }
}
